// Code generated by genproto. DO NOT EDIT.

package xmlpb

import "github.com/accretional/xmile/lex"

// Lexical maps each token-matcher name to its lexical rule.
var Lexical = map[string]lex.Matcher{
	"Char": {Kind: "run", Ranges: []lex.Range{{Lo: 0x9, Hi: 0x9}, {Lo: 0xA, Hi: 0xA}, {Lo: 0xD, Hi: 0xD}, {Lo: 0x20, Hi: 0xD7FF}, {Lo: 0xE000, Hi: 0xFFFD}, {Lo: 0x10000, Hi: 0x10FFFF}}},
	"CharData": {Kind: "except", Stops: "<&"},
	"Name": {Kind: "name", Ranges: []lex.Range{{Lo: 0x3A, Hi: 0x3A}, {Lo: 0x5F, Hi: 0x5F}, {Lo: 0x41, Hi: 0x5A}, {Lo: 0x61, Hi: 0x7A}, {Lo: 0xC0, Hi: 0xD6}, {Lo: 0xD8, Hi: 0xF6}, {Lo: 0xF8, Hi: 0x2FF}, {Lo: 0x370, Hi: 0x37D}, {Lo: 0x37F, Hi: 0x1FFF}, {Lo: 0x200C, Hi: 0x200D}, {Lo: 0x2070, Hi: 0x218F}, {Lo: 0x2C00, Hi: 0x2FEF}, {Lo: 0x3001, Hi: 0xD7FF}, {Lo: 0xF900, Hi: 0xFDCF}, {Lo: 0xFDF0, Hi: 0xFFFD}, {Lo: 0x10000, Hi: 0xEFFFF}}, Rest: []lex.Range{{Lo: 0x2D, Hi: 0x2D}, {Lo: 0x2E, Hi: 0x2E}, {Lo: 0x30, Hi: 0x39}, {Lo: 0xB7, Hi: 0xB7}, {Lo: 0x300, Hi: 0x36F}, {Lo: 0x203F, Hi: 0x2040}}},
	"S": {Kind: "run", Ranges: []lex.Range{{Lo: 0x9, Hi: 0x9}, {Lo: 0xA, Hi: 0xA}, {Lo: 0xD, Hi: 0xD}, {Lo: 0x20, Hi: 0x20}}},
	"cdata_text": {Kind: "until", Delim: "]]>"},
	"comment_text": {Kind: "until", Delim: "--"},
	"dqText": {Kind: "except", Stops: "\"<&"},
	"dtd_text": {Kind: "balanced"},
	"pi_text": {Kind: "until", Delim: "?>"},
	"sqText": {Kind: "except", Stops: "'<&"},
	"xmldecl_text": {Kind: "until", Delim: "?>"},
}
