// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: xml.proto

package xmlpb

import (
	dtd "github.com/accretional/xmile/proto/pb/dtd"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Document is the root of a parsed XML document.
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// <?xml version="1.0" encoding="…" standalone="…"?>, if present.
	XmlDecl *XmlDecl `protobuf:"bytes,1,opt,name=xml_decl,json=xmlDecl,proto3" json:"xml_decl,omitempty"`
	// The DOCTYPE, if present. Its body — root name, external ID, and the
	// inline internal subset's declarations — is parsed by lang/dtd.ebnf and
	// represented by the generated dtd.Doctype. nil when there is no DOCTYPE.
	Doctype *dtd.Doctype `protobuf:"bytes,2,opt,name=doctype,proto3" json:"doctype,omitempty"`
	// Comments / PIs in the prolog (before the root element).
	PrologMisc []*Misc `protobuf:"bytes,3,rep,name=prolog_misc,json=prologMisc,proto3" json:"prolog_misc,omitempty"`
	// The single root element.
	Root *Tag `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	// Comments / PIs after the root element (the epilog).
	EpilogMisc    []*Misc `protobuf:"bytes,5,rep,name=epilog_misc,json=epilogMisc,proto3" json:"epilog_misc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_xml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_xml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_xml_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetXmlDecl() *XmlDecl {
	if x != nil {
		return x.XmlDecl
	}
	return nil
}

func (x *Document) GetDoctype() *dtd.Doctype {
	if x != nil {
		return x.Doctype
	}
	return nil
}

func (x *Document) GetPrologMisc() []*Misc {
	if x != nil {
		return x.PrologMisc
	}
	return nil
}

func (x *Document) GetRoot() *Tag {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *Document) GetEpilogMisc() []*Misc {
	if x != nil {
		return x.EpilogMisc
	}
	return nil
}

// XmlDecl is the optional XML declaration.
type XmlDecl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`       // e.g. "1.0"
	Encoding      string                 `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"`     // e.g. "UTF-8"; empty if absent
	Standalone    string                 `protobuf:"bytes,3,opt,name=standalone,proto3" json:"standalone,omitempty"` // "yes" / "no"; empty if absent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XmlDecl) Reset() {
	*x = XmlDecl{}
	mi := &file_xml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XmlDecl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XmlDecl) ProtoMessage() {}

func (x *XmlDecl) ProtoReflect() protoreflect.Message {
	mi := &file_xml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XmlDecl.ProtoReflect.Descriptor instead.
func (*XmlDecl) Descriptor() ([]byte, []int) {
	return file_xml_proto_rawDescGZIP(), []int{1}
}

func (x *XmlDecl) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *XmlDecl) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *XmlDecl) GetStandalone() string {
	if x != nil {
		return x.Standalone
	}
	return ""
}

// Tag is an element node. Homogeneous across all element types.
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Attrs         []*Attribute           `protobuf:"bytes,2,rep,name=attrs,proto3" json:"attrs,omitempty"`
	Contents      []*ContentItem         `protobuf:"bytes,3,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_xml_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_xml_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_xml_proto_rawDescGZIP(), []int{2}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetAttrs() []*Attribute {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *Tag) GetContents() []*ContentItem {
	if x != nil {
		return x.Contents
	}
	return nil
}

// Attribute is one name=value pair. The value is normalized: entity and
// character references are resolved and whitespace is normalized per the
// declared type.
type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_xml_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_xml_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_xml_proto_rawDescGZIP(), []int{3}
}

func (x *Attribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ContentItem is one item in an element's content. References (entity /
// character) are resolved during parsing and therefore never appear here:
// they fold into `text` or, for markup-bearing entities, into `child`.
type ContentItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*ContentItem_Text
	//	*ContentItem_Child
	//	*ContentItem_Cdata
	//	*ContentItem_Comment
	//	*ContentItem_Pi
	Item          isContentItem_Item `protobuf_oneof:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentItem) Reset() {
	*x = ContentItem{}
	mi := &file_xml_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentItem) ProtoMessage() {}

func (x *ContentItem) ProtoReflect() protoreflect.Message {
	mi := &file_xml_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentItem.ProtoReflect.Descriptor instead.
func (*ContentItem) Descriptor() ([]byte, []int) {
	return file_xml_proto_rawDescGZIP(), []int{4}
}

func (x *ContentItem) GetItem() isContentItem_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ContentItem) GetText() string {
	if x != nil {
		if x, ok := x.Item.(*ContentItem_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ContentItem) GetChild() *Tag {
	if x != nil {
		if x, ok := x.Item.(*ContentItem_Child); ok {
			return x.Child
		}
	}
	return nil
}

func (x *ContentItem) GetCdata() string {
	if x != nil {
		if x, ok := x.Item.(*ContentItem_Cdata); ok {
			return x.Cdata
		}
	}
	return ""
}

func (x *ContentItem) GetComment() string {
	if x != nil {
		if x, ok := x.Item.(*ContentItem_Comment); ok {
			return x.Comment
		}
	}
	return ""
}

func (x *ContentItem) GetPi() *PI {
	if x != nil {
		if x, ok := x.Item.(*ContentItem_Pi); ok {
			return x.Pi
		}
	}
	return nil
}

type isContentItem_Item interface {
	isContentItem_Item()
}

type ContentItem_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"` // character data
}

type ContentItem_Child struct {
	Child *Tag `protobuf:"bytes,2,opt,name=child,proto3,oneof"` // nested element
}

type ContentItem_Cdata struct {
	Cdata string `protobuf:"bytes,3,opt,name=cdata,proto3,oneof"` // raw text from <![CDATA[ … ]]>
}

type ContentItem_Comment struct {
	Comment string `protobuf:"bytes,4,opt,name=comment,proto3,oneof"` // text from <!-- … -->
}

type ContentItem_Pi struct {
	Pi *PI `protobuf:"bytes,5,opt,name=pi,proto3,oneof"` // a processing instruction
}

func (*ContentItem_Text) isContentItem_Item() {}

func (*ContentItem_Child) isContentItem_Item() {}

func (*ContentItem_Cdata) isContentItem_Item() {}

func (*ContentItem_Comment) isContentItem_Item() {}

func (*ContentItem_Pi) isContentItem_Item() {}

// PI is a processing instruction: <?target data?> (target != "xml").
type PI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PI) Reset() {
	*x = PI{}
	mi := &file_xml_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PI) ProtoMessage() {}

func (x *PI) ProtoReflect() protoreflect.Message {
	mi := &file_xml_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PI.ProtoReflect.Descriptor instead.
func (*PI) Descriptor() ([]byte, []int) {
	return file_xml_proto_rawDescGZIP(), []int{5}
}

func (x *PI) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PI) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Misc is a prolog/epilog item: a comment or a PI. Insignificant
// whitespace between them is not retained.
type Misc struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*Misc_Comment
	//	*Misc_Pi
	Item          isMisc_Item `protobuf_oneof:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Misc) Reset() {
	*x = Misc{}
	mi := &file_xml_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Misc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Misc) ProtoMessage() {}

func (x *Misc) ProtoReflect() protoreflect.Message {
	mi := &file_xml_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Misc.ProtoReflect.Descriptor instead.
func (*Misc) Descriptor() ([]byte, []int) {
	return file_xml_proto_rawDescGZIP(), []int{6}
}

func (x *Misc) GetItem() isMisc_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *Misc) GetComment() string {
	if x != nil {
		if x, ok := x.Item.(*Misc_Comment); ok {
			return x.Comment
		}
	}
	return ""
}

func (x *Misc) GetPi() *PI {
	if x != nil {
		if x, ok := x.Item.(*Misc_Pi); ok {
			return x.Pi
		}
	}
	return nil
}

type isMisc_Item interface {
	isMisc_Item()
}

type Misc_Comment struct {
	Comment string `protobuf:"bytes,1,opt,name=comment,proto3,oneof"`
}

type Misc_Pi struct {
	Pi *PI `protobuf:"bytes,2,opt,name=pi,proto3,oneof"`
}

func (*Misc_Comment) isMisc_Item() {}

func (*Misc_Pi) isMisc_Item() {}

var File_xml_proto protoreflect.FileDescriptor

const file_xml_proto_rawDesc = "" +
	"\n" +
	"\txml.proto\x12\x03xml\x1a\tdtd.proto\"\xd1\x01\n" +
	"\bDocument\x12'\n" +
	"\bxml_decl\x18\x01 \x01(\v2\f.xml.XmlDeclR\axmlDecl\x12&\n" +
	"\adoctype\x18\x02 \x01(\v2\f.dtd.DoctypeR\adoctype\x12*\n" +
	"\vprolog_misc\x18\x03 \x03(\v2\t.xml.MiscR\n" +
	"prologMisc\x12\x1c\n" +
	"\x04root\x18\x04 \x01(\v2\b.xml.TagR\x04root\x12*\n" +
	"\vepilog_misc\x18\x05 \x03(\v2\t.xml.MiscR\n" +
	"epilogMisc\"_\n" +
	"\aXmlDecl\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\tR\bencoding\x12\x1e\n" +
	"\n" +
	"standalone\x18\x03 \x01(\tR\n" +
	"standalone\"m\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\x05attrs\x18\x02 \x03(\v2\x0e.xml.AttributeR\x05attrs\x12,\n" +
	"\bcontents\x18\x03 \x03(\v2\x10.xml.ContentItemR\bcontents\"5\n" +
	"\tAttribute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x9c\x01\n" +
	"\vContentItem\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12 \n" +
	"\x05child\x18\x02 \x01(\v2\b.xml.TagH\x00R\x05child\x12\x16\n" +
	"\x05cdata\x18\x03 \x01(\tH\x00R\x05cdata\x12\x1a\n" +
	"\acomment\x18\x04 \x01(\tH\x00R\acomment\x12\x19\n" +
	"\x02pi\x18\x05 \x01(\v2\a.xml.PIH\x00R\x02piB\x06\n" +
	"\x04item\"0\n" +
	"\x02PI\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"E\n" +
	"\x04Misc\x12\x1a\n" +
	"\acomment\x18\x01 \x01(\tH\x00R\acomment\x12\x19\n" +
	"\x02pi\x18\x02 \x01(\v2\a.xml.PIH\x00R\x02piB\x06\n" +
	"\x04itemB1Z/github.com/accretional/xmile/proto/pb/xml;xmlpbb\x06proto3"

var (
	file_xml_proto_rawDescOnce sync.Once
	file_xml_proto_rawDescData []byte
)

func file_xml_proto_rawDescGZIP() []byte {
	file_xml_proto_rawDescOnce.Do(func() {
		file_xml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xml_proto_rawDesc), len(file_xml_proto_rawDesc)))
	})
	return file_xml_proto_rawDescData
}

var file_xml_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_xml_proto_goTypes = []any{
	(*Document)(nil),    // 0: xml.Document
	(*XmlDecl)(nil),     // 1: xml.XmlDecl
	(*Tag)(nil),         // 2: xml.Tag
	(*Attribute)(nil),   // 3: xml.Attribute
	(*ContentItem)(nil), // 4: xml.ContentItem
	(*PI)(nil),          // 5: xml.PI
	(*Misc)(nil),        // 6: xml.Misc
	(*dtd.Doctype)(nil), // 7: dtd.Doctype
}
var file_xml_proto_depIdxs = []int32{
	1,  // 0: xml.Document.xml_decl:type_name -> xml.XmlDecl
	7,  // 1: xml.Document.doctype:type_name -> dtd.Doctype
	6,  // 2: xml.Document.prolog_misc:type_name -> xml.Misc
	2,  // 3: xml.Document.root:type_name -> xml.Tag
	6,  // 4: xml.Document.epilog_misc:type_name -> xml.Misc
	3,  // 5: xml.Tag.attrs:type_name -> xml.Attribute
	4,  // 6: xml.Tag.contents:type_name -> xml.ContentItem
	2,  // 7: xml.ContentItem.child:type_name -> xml.Tag
	5,  // 8: xml.ContentItem.pi:type_name -> xml.PI
	5,  // 9: xml.Misc.pi:type_name -> xml.PI
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_xml_proto_init() }
func file_xml_proto_init() {
	if File_xml_proto != nil {
		return
	}
	file_xml_proto_msgTypes[4].OneofWrappers = []any{
		(*ContentItem_Text)(nil),
		(*ContentItem_Child)(nil),
		(*ContentItem_Cdata)(nil),
		(*ContentItem_Comment)(nil),
		(*ContentItem_Pi)(nil),
	}
	file_xml_proto_msgTypes[6].OneofWrappers = []any{
		(*Misc_Comment)(nil),
		(*Misc_Pi)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xml_proto_rawDesc), len(file_xml_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xml_proto_goTypes,
		DependencyIndexes: file_xml_proto_depIdxs,
		MessageInfos:      file_xml_proto_msgTypes,
	}.Build()
	File_xml_proto = out.File
	file_xml_proto_goTypes = nil
	file_xml_proto_depIdxs = nil
}
