// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: xml_service.proto

package xmlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Documents_Process_FullMethodName  = "/xml.Documents/Process"
	Documents_Generate_FullMethodName = "/xml.Documents/Generate"
)

// DocumentsClient is the client API for Documents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Documents is the instance-level service: bytes (+ optional schema) -> result,
// and the reverse — an AST -> bytes.
type DocumentsClient interface {
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
	// Generate is the inverse of Process: it serializes the generic XML AST back
	// to a document. It walks the homogeneous Tag tree (no schema, no reflection)
	// and re-escapes character data, so parse(Generate(parse(b))) == parse(b).
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
}

type documentsClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentsClient(cc grpc.ClientConnInterface) DocumentsClient {
	return &documentsClient{cc}
}

func (c *documentsClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, Documents_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, Documents_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentsServer is the server API for Documents service.
// All implementations must embed UnimplementedDocumentsServer
// for forward compatibility.
//
// Documents is the instance-level service: bytes (+ optional schema) -> result,
// and the reverse — an AST -> bytes.
type DocumentsServer interface {
	Process(context.Context, *ProcessRequest) (*ProcessResponse, error)
	// Generate is the inverse of Process: it serializes the generic XML AST back
	// to a document. It walks the homogeneous Tag tree (no schema, no reflection)
	// and re-escapes character data, so parse(Generate(parse(b))) == parse(b).
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	mustEmbedUnimplementedDocumentsServer()
}

// UnimplementedDocumentsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentsServer struct{}

func (UnimplementedDocumentsServer) Process(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedDocumentsServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedDocumentsServer) mustEmbedUnimplementedDocumentsServer() {}
func (UnimplementedDocumentsServer) testEmbeddedByValue()                   {}

// UnsafeDocumentsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentsServer will
// result in compilation errors.
type UnsafeDocumentsServer interface {
	mustEmbedUnimplementedDocumentsServer()
}

func RegisterDocumentsServer(s grpc.ServiceRegistrar, srv DocumentsServer) {
	// If the following call panics, it indicates UnimplementedDocumentsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Documents_ServiceDesc, srv)
}

func _Documents_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Documents_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).Process(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documents_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Documents_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Documents_ServiceDesc is the grpc.ServiceDesc for Documents service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Documents_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xml.Documents",
	HandlerType: (*DocumentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _Documents_Process_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _Documents_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xml_service.proto",
}

const (
	Schemas_Compile_FullMethodName = "/xml.Schemas/Compile"
)

// SchemasClient is the client API for Schemas service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Schemas is the type-level service: a metagrammar -> a proto descriptor.
type SchemasClient interface {
	Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error)
}

type schemasClient struct {
	cc grpc.ClientConnInterface
}

func NewSchemasClient(cc grpc.ClientConnInterface) SchemasClient {
	return &schemasClient{cc}
}

func (c *schemasClient) Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompileResponse)
	err := c.cc.Invoke(ctx, Schemas_Compile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchemasServer is the server API for Schemas service.
// All implementations must embed UnimplementedSchemasServer
// for forward compatibility.
//
// Schemas is the type-level service: a metagrammar -> a proto descriptor.
type SchemasServer interface {
	Compile(context.Context, *CompileRequest) (*CompileResponse, error)
	mustEmbedUnimplementedSchemasServer()
}

// UnimplementedSchemasServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchemasServer struct{}

func (UnimplementedSchemasServer) Compile(context.Context, *CompileRequest) (*CompileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compile not implemented")
}
func (UnimplementedSchemasServer) mustEmbedUnimplementedSchemasServer() {}
func (UnimplementedSchemasServer) testEmbeddedByValue()                 {}

// UnsafeSchemasServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchemasServer will
// result in compilation errors.
type UnsafeSchemasServer interface {
	mustEmbedUnimplementedSchemasServer()
}

func RegisterSchemasServer(s grpc.ServiceRegistrar, srv SchemasServer) {
	// If the following call panics, it indicates UnimplementedSchemasServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Schemas_ServiceDesc, srv)
}

func _Schemas_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchemasServer).Compile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Schemas_Compile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchemasServer).Compile(ctx, req.(*CompileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Schemas_ServiceDesc is the grpc.ServiceDesc for Schemas service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Schemas_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xml.Schemas",
	HandlerType: (*SchemasServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compile",
			Handler:    _Schemas_Compile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xml_service.proto",
}
