// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: xml_service.proto

package xmlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Verdict classifies a Process outcome.
type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED Verdict = 0
	Verdict_NOT_WELL_FORMED     Verdict = 1 // syntactically not a document
	Verdict_WELL_FORMED         Verdict = 2 // accepted, not validated (no schema, project-only)
	Verdict_VALID               Verdict = 3 // accepted and validated against its schema / DTD
	Verdict_INVALID             Verdict = 4 // well-formed but breaks its schema / DTD
	Verdict_CANNOT_VALIDATE     Verdict = 5 // validation requested but the DTD cannot be fully read
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "NOT_WELL_FORMED",
		2: "WELL_FORMED",
		3: "VALID",
		4: "INVALID",
		5: "CANNOT_VALIDATE",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED": 0,
		"NOT_WELL_FORMED":     1,
		"WELL_FORMED":         2,
		"VALID":               3,
		"INVALID":             4,
		"CANNOT_VALIDATE":     5,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_xml_service_proto_enumTypes[0].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_xml_service_proto_enumTypes[0]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_ERROR                Severity = 1
	Severity_WARNING              Severity = 2
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "ERROR",
		2: "WARNING",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"ERROR":                1,
		"WARNING":              2,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_xml_service_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_xml_service_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{1}
}

type Mode int32

const (
	Mode_PROJECT_ONLY Mode = 0 // parse / project and report; do not enforce validity
	Mode_VALIDATE     Mode = 1 // enforce validity (the DTD for generic XML; vocabulary coverage for a schema)
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "PROJECT_ONLY",
		1: "VALIDATE",
	}
	Mode_value = map[string]int32{
		"PROJECT_ONLY": 0,
		"VALIDATE":     1,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_xml_service_proto_enumTypes[2].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_xml_service_proto_enumTypes[2]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{2}
}

type SchemaLanguage int32

const (
	SchemaLanguage_SCHEMA_LANGUAGE_UNSPECIFIED SchemaLanguage = 0 // treated as EBNF_VOCAB
	SchemaLanguage_DTD                         SchemaLanguage = 1
	SchemaLanguage_EBNF_VOCAB                  SchemaLanguage = 2
	SchemaLanguage_XSD                         SchemaLanguage = 3
)

// Enum value maps for SchemaLanguage.
var (
	SchemaLanguage_name = map[int32]string{
		0: "SCHEMA_LANGUAGE_UNSPECIFIED",
		1: "DTD",
		2: "EBNF_VOCAB",
		3: "XSD",
	}
	SchemaLanguage_value = map[string]int32{
		"SCHEMA_LANGUAGE_UNSPECIFIED": 0,
		"DTD":                         1,
		"EBNF_VOCAB":                  2,
		"XSD":                         3,
	}
)

func (x SchemaLanguage) Enum() *SchemaLanguage {
	p := new(SchemaLanguage)
	*p = x
	return p
}

func (x SchemaLanguage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchemaLanguage) Descriptor() protoreflect.EnumDescriptor {
	return file_xml_service_proto_enumTypes[3].Descriptor()
}

func (SchemaLanguage) Type() protoreflect.EnumType {
	return &file_xml_service_proto_enumTypes[3]
}

func (x SchemaLanguage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchemaLanguage.Descriptor instead.
func (SchemaLanguage) EnumDescriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{3}
}

// Diagnostic is a non-fatal finding (soft conformance), severity-tagged so a
// vocabulary's "SHOULD" rules are reported without failing the parse.
type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      Severity               `protobuf:"varint,1,opt,name=severity,proto3,enum=xml.Severity" json:"severity,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_xml_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{0}
}

func (x *Diagnostic) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Diagnostic) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ProcessRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Source []byte                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// schema selects the vocabulary to project into. Unset -> generic XML (the
	// homogeneous Tag tree, i.e. the former Parse). A registered format name or
	// an inline metagrammar compile projects into that vocabulary's typed tree.
	//
	// Types that are valid to be assigned to Schema:
	//
	//	*ProcessRequest_Format
	//	*ProcessRequest_Compile
	Schema        isProcessRequest_Schema `protobuf_oneof:"schema"`
	Mode          Mode                    `protobuf:"varint,4,opt,name=mode,proto3,enum=xml.Mode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_xml_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessRequest) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ProcessRequest) GetSchema() isProcessRequest_Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ProcessRequest) GetFormat() string {
	if x != nil {
		if x, ok := x.Schema.(*ProcessRequest_Format); ok {
			return x.Format
		}
	}
	return ""
}

func (x *ProcessRequest) GetCompile() *CompileRequest {
	if x != nil {
		if x, ok := x.Schema.(*ProcessRequest_Compile); ok {
			return x.Compile
		}
	}
	return nil
}

func (x *ProcessRequest) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_PROJECT_ONLY
}

type isProcessRequest_Schema interface {
	isProcessRequest_Schema()
}

type ProcessRequest_Format struct {
	Format string `protobuf:"bytes,2,opt,name=format,proto3,oneof"` // a registered format, e.g. "rss-2.0"
}

type ProcessRequest_Compile struct {
	Compile *CompileRequest `protobuf:"bytes,3,opt,name=compile,proto3,oneof"` // compile a metagrammar, then project against it
}

func (*ProcessRequest_Format) isProcessRequest_Schema() {}

func (*ProcessRequest_Compile) isProcessRequest_Schema() {}

type ProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ProcessResponse_Document
	//	*ProcessResponse_Error
	Result        isProcessResponse_Result `protobuf_oneof:"result"`
	Verdict       Verdict                  `protobuf:"varint,3,opt,name=verdict,proto3,enum=xml.Verdict" json:"verdict,omitempty"`
	Diagnostics   []*Diagnostic            `protobuf:"bytes,4,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"` // soft conformance (severity WARNING)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_xml_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessResponse) GetResult() isProcessResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ProcessResponse) GetDocument() *structpb.Struct {
	if x != nil {
		if x, ok := x.Result.(*ProcessResponse_Document); ok {
			return x.Document
		}
	}
	return nil
}

func (x *ProcessResponse) GetError() *ProcessError {
	if x != nil {
		if x, ok := x.Result.(*ProcessResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ProcessResponse) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *ProcessResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type isProcessResponse_Result interface {
	isProcessResponse_Result()
}

type ProcessResponse_Document struct {
	Document *structpb.Struct `protobuf:"bytes,1,opt,name=document,proto3,oneof"` // a schema: the projected AST, keyed by the root element (e.g. {"rss": {...}})
}

type ProcessResponse_Error struct {
	Error *ProcessError `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // refusal
}

func (*ProcessResponse_Document) isProcessResponse_Result() {}

func (*ProcessResponse_Error) isProcessResponse_Result() {}

type ProcessError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       Verdict                `protobuf:"varint,1,opt,name=verdict,proto3,enum=xml.Verdict" json:"verdict,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessError) Reset() {
	*x = ProcessError{}
	mi := &file_xml_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessError) ProtoMessage() {}

func (x *ProcessError) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessError.ProtoReflect.Descriptor instead.
func (*ProcessError) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessError) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *ProcessError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// GenerateRequest carries the generic XML AST to serialize. It is the typed Xml
// tree, not a free-form Struct: only the lossless generic AST round-trips, so a
// format's typed projection — a read-only view that may have dropped unmodeled
// markup — is not even representable here.
type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Xml                   `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_xml_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateRequest) GetDocument() *Xml {
	if x != nil {
		return x.Document
	}
	return nil
}

type GenerateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GenerateResponse_Source
	//	*GenerateResponse_Error
	Result        isGenerateResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_xml_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateResponse) GetResult() isGenerateResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GenerateResponse) GetSource() []byte {
	if x != nil {
		if x, ok := x.Result.(*GenerateResponse_Source); ok {
			return x.Source
		}
	}
	return nil
}

func (x *GenerateResponse) GetError() *GenerateError {
	if x != nil {
		if x, ok := x.Result.(*GenerateResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGenerateResponse_Result interface {
	isGenerateResponse_Result()
}

type GenerateResponse_Source struct {
	Source []byte `protobuf:"bytes,1,opt,name=source,proto3,oneof"` // the serialized XML document
}

type GenerateResponse_Error struct {
	Error *GenerateError `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // refusal (e.g. a typed tree, or a malformed AST)
}

func (*GenerateResponse_Source) isGenerateResponse_Result() {}

func (*GenerateResponse_Error) isGenerateResponse_Result() {}

type GenerateError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateError) Reset() {
	*x = GenerateError{}
	mi := &file_xml_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateError) ProtoMessage() {}

func (x *GenerateError) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateError.ProtoReflect.Descriptor instead.
func (*GenerateError) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CompileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        []byte                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Language      SchemaLanguage         `protobuf:"varint,2,opt,name=language,proto3,enum=xml.SchemaLanguage" json:"language,omitempty"`
	Package       string                 `protobuf:"bytes,3,opt,name=package,proto3" json:"package,omitempty"`                      // proto package (e.g. "rss"); defaults to "lang"
	GoPackage     string                 `protobuf:"bytes,4,opt,name=go_package,json=goPackage,proto3" json:"go_package,omitempty"` // go_package file option; omitted if empty
	FileName      string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`    // FileDescriptorProto.name; "<package>.proto" default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_xml_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{7}
}

func (x *CompileRequest) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *CompileRequest) GetLanguage() SchemaLanguage {
	if x != nil {
		return x.Language
	}
	return SchemaLanguage_SCHEMA_LANGUAGE_UNSPECIFIED
}

func (x *CompileRequest) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *CompileRequest) GetGoPackage() string {
	if x != nil {
		return x.GoPackage
	}
	return ""
}

func (x *CompileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type CompileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CompileResponse_File
	//	*CompileResponse_Error
	Result        isCompileResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_xml_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{8}
}

func (x *CompileResponse) GetResult() isCompileResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CompileResponse) GetFile() *descriptorpb.FileDescriptorProto {
	if x != nil {
		if x, ok := x.Result.(*CompileResponse_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *CompileResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*CompileResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isCompileResponse_Result interface {
	isCompileResponse_Result()
}

type CompileResponse_File struct {
	File *descriptorpb.FileDescriptorProto `protobuf:"bytes,1,opt,name=file,proto3,oneof"`
}

type CompileResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CompileResponse_File) isCompileResponse_Result() {}

func (*CompileResponse_Error) isCompileResponse_Result() {}

var File_xml_service_proto protoreflect.FileDescriptor

const file_xml_service_proto_rawDesc = "" +
	"\n" +
	"\x11xml_service.proto\x12\x03xml\x1a google/protobuf/descriptor.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\txml.proto\"O\n" +
	"\n" +
	"Diagnostic\x12)\n" +
	"\bseverity\x18\x01 \x01(\x0e2\r.xml.SeverityR\bseverity\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x9c\x01\n" +
	"\x0eProcessRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\fR\x06source\x12\x18\n" +
	"\x06format\x18\x02 \x01(\tH\x00R\x06format\x12/\n" +
	"\acompile\x18\x03 \x01(\v2\x13.xml.CompileRequestH\x00R\acompile\x12\x1d\n" +
	"\x04mode\x18\x04 \x01(\x0e2\t.xml.ModeR\x04modeB\b\n" +
	"\x06schema\"\xd8\x01\n" +
	"\x0fProcessResponse\x125\n" +
	"\bdocument\x18\x01 \x01(\v2\x17.google.protobuf.StructH\x00R\bdocument\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.xml.ProcessErrorH\x00R\x05error\x12&\n" +
	"\averdict\x18\x03 \x01(\x0e2\f.xml.VerdictR\averdict\x121\n" +
	"\vdiagnostics\x18\x04 \x03(\v2\x0f.xml.DiagnosticR\vdiagnosticsB\b\n" +
	"\x06result\"N\n" +
	"\fProcessError\x12&\n" +
	"\averdict\x18\x01 \x01(\x0e2\f.xml.VerdictR\averdict\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"7\n" +
	"\x0fGenerateRequest\x12$\n" +
	"\bdocument\x18\x01 \x01(\v2\b.xml.XmlR\bdocument\"b\n" +
	"\x10GenerateResponse\x12\x18\n" +
	"\x06source\x18\x01 \x01(\fH\x00R\x06source\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.xml.GenerateErrorH\x00R\x05errorB\b\n" +
	"\x06result\"'\n" +
	"\rGenerateError\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xaf\x01\n" +
	"\x0eCompileRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\fR\x06source\x12/\n" +
	"\blanguage\x18\x02 \x01(\x0e2\x13.xml.SchemaLanguageR\blanguage\x12\x18\n" +
	"\apackage\x18\x03 \x01(\tR\apackage\x12\x1d\n" +
	"\n" +
	"go_package\x18\x04 \x01(\tR\tgoPackage\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\"o\n" +
	"\x0fCompileResponse\x12:\n" +
	"\x04file\x18\x01 \x01(\v2$.google.protobuf.FileDescriptorProtoH\x00R\x04file\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result*u\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fNOT_WELL_FORMED\x10\x01\x12\x0f\n" +
	"\vWELL_FORMED\x10\x02\x12\t\n" +
	"\x05VALID\x10\x03\x12\v\n" +
	"\aINVALID\x10\x04\x12\x13\n" +
	"\x0fCANNOT_VALIDATE\x10\x05*<\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02*&\n" +
	"\x04Mode\x12\x10\n" +
	"\fPROJECT_ONLY\x10\x00\x12\f\n" +
	"\bVALIDATE\x10\x01*S\n" +
	"\x0eSchemaLanguage\x12\x1f\n" +
	"\x1bSCHEMA_LANGUAGE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03DTD\x10\x01\x12\x0e\n" +
	"\n" +
	"EBNF_VOCAB\x10\x02\x12\a\n" +
	"\x03XSD\x10\x032z\n" +
	"\tDocuments\x124\n" +
	"\aProcess\x12\x13.xml.ProcessRequest\x1a\x14.xml.ProcessResponse\x127\n" +
	"\bGenerate\x12\x14.xml.GenerateRequest\x1a\x15.xml.GenerateResponse2?\n" +
	"\aSchemas\x124\n" +
	"\aCompile\x12\x13.xml.CompileRequest\x1a\x14.xml.CompileResponseB1Z/github.com/accretional/xmile/proto/pb/xml;xmlpbb\x06proto3"

var (
	file_xml_service_proto_rawDescOnce sync.Once
	file_xml_service_proto_rawDescData []byte
)

func file_xml_service_proto_rawDescGZIP() []byte {
	file_xml_service_proto_rawDescOnce.Do(func() {
		file_xml_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xml_service_proto_rawDesc), len(file_xml_service_proto_rawDesc)))
	})
	return file_xml_service_proto_rawDescData
}

var file_xml_service_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_xml_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_xml_service_proto_goTypes = []any{
	(Verdict)(0),                             // 0: xml.Verdict
	(Severity)(0),                            // 1: xml.Severity
	(Mode)(0),                                // 2: xml.Mode
	(SchemaLanguage)(0),                      // 3: xml.SchemaLanguage
	(*Diagnostic)(nil),                       // 4: xml.Diagnostic
	(*ProcessRequest)(nil),                   // 5: xml.ProcessRequest
	(*ProcessResponse)(nil),                  // 6: xml.ProcessResponse
	(*ProcessError)(nil),                     // 7: xml.ProcessError
	(*GenerateRequest)(nil),                  // 8: xml.GenerateRequest
	(*GenerateResponse)(nil),                 // 9: xml.GenerateResponse
	(*GenerateError)(nil),                    // 10: xml.GenerateError
	(*CompileRequest)(nil),                   // 11: xml.CompileRequest
	(*CompileResponse)(nil),                  // 12: xml.CompileResponse
	(*structpb.Struct)(nil),                  // 13: google.protobuf.Struct
	(*Xml)(nil),                              // 14: xml.Xml
	(*descriptorpb.FileDescriptorProto)(nil), // 15: google.protobuf.FileDescriptorProto
}
var file_xml_service_proto_depIdxs = []int32{
	1,  // 0: xml.Diagnostic.severity:type_name -> xml.Severity
	11, // 1: xml.ProcessRequest.compile:type_name -> xml.CompileRequest
	2,  // 2: xml.ProcessRequest.mode:type_name -> xml.Mode
	13, // 3: xml.ProcessResponse.document:type_name -> google.protobuf.Struct
	7,  // 4: xml.ProcessResponse.error:type_name -> xml.ProcessError
	0,  // 5: xml.ProcessResponse.verdict:type_name -> xml.Verdict
	4,  // 6: xml.ProcessResponse.diagnostics:type_name -> xml.Diagnostic
	0,  // 7: xml.ProcessError.verdict:type_name -> xml.Verdict
	14, // 8: xml.GenerateRequest.document:type_name -> xml.Xml
	10, // 9: xml.GenerateResponse.error:type_name -> xml.GenerateError
	3,  // 10: xml.CompileRequest.language:type_name -> xml.SchemaLanguage
	15, // 11: xml.CompileResponse.file:type_name -> google.protobuf.FileDescriptorProto
	5,  // 12: xml.Documents.Process:input_type -> xml.ProcessRequest
	8,  // 13: xml.Documents.Generate:input_type -> xml.GenerateRequest
	11, // 14: xml.Schemas.Compile:input_type -> xml.CompileRequest
	6,  // 15: xml.Documents.Process:output_type -> xml.ProcessResponse
	9,  // 16: xml.Documents.Generate:output_type -> xml.GenerateResponse
	12, // 17: xml.Schemas.Compile:output_type -> xml.CompileResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_xml_service_proto_init() }
func file_xml_service_proto_init() {
	if File_xml_service_proto != nil {
		return
	}
	file_xml_proto_init()
	file_xml_service_proto_msgTypes[1].OneofWrappers = []any{
		(*ProcessRequest_Format)(nil),
		(*ProcessRequest_Compile)(nil),
	}
	file_xml_service_proto_msgTypes[2].OneofWrappers = []any{
		(*ProcessResponse_Document)(nil),
		(*ProcessResponse_Error)(nil),
	}
	file_xml_service_proto_msgTypes[5].OneofWrappers = []any{
		(*GenerateResponse_Source)(nil),
		(*GenerateResponse_Error)(nil),
	}
	file_xml_service_proto_msgTypes[8].OneofWrappers = []any{
		(*CompileResponse_File)(nil),
		(*CompileResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xml_service_proto_rawDesc), len(file_xml_service_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_xml_service_proto_goTypes,
		DependencyIndexes: file_xml_service_proto_depIdxs,
		EnumInfos:         file_xml_service_proto_enumTypes,
		MessageInfos:      file_xml_service_proto_msgTypes,
	}.Build()
	File_xml_service_proto = out.File
	file_xml_service_proto_goTypes = nil
	file_xml_service_proto_depIdxs = nil
}
