// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: xml_service.proto

package xmlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Verdict classifies why a document was refused.
type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED Verdict = 0
	Verdict_NOT_WELL_FORMED     Verdict = 1 // syntactically not a document
	Verdict_INVALID             Verdict = 2 // well-formed but breaks its DTD (validate=true)
	Verdict_CANNOT_VALIDATE     Verdict = 3 // validate=true, but the DTD cannot be fully read
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "NOT_WELL_FORMED",
		2: "INVALID",
		3: "CANNOT_VALIDATE",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED": 0,
		"NOT_WELL_FORMED":     1,
		"INVALID":             2,
		"CANNOT_VALIDATE":     3,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_xml_service_proto_enumTypes[0].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_xml_service_proto_enumTypes[0]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{0}
}

type ParseRssRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xml           []byte                 `protobuf:"bytes,1,opt,name=xml,proto3" json:"xml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRssRequest) Reset() {
	*x = ParseRssRequest{}
	mi := &file_xml_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRssRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRssRequest) ProtoMessage() {}

func (x *ParseRssRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRssRequest.ProtoReflect.Descriptor instead.
func (*ParseRssRequest) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRssRequest) GetXml() []byte {
	if x != nil {
		return x.Xml
	}
	return nil
}

type ParseRssResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The typed RSS AST (an rss.Rss, carried as Any so the service need not link
	// the generated Go type — decode it with the descriptor from a schema
	// compile of lang/rss.ebnf) on acceptance, or a ParseError on refusal.
	//
	// Types that are valid to be assigned to Response:
	//
	//	*ParseRssResponse_Rss
	//	*ParseRssResponse_Error
	Response      isParseRssResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRssResponse) Reset() {
	*x = ParseRssResponse{}
	mi := &file_xml_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRssResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRssResponse) ProtoMessage() {}

func (x *ParseRssResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRssResponse.ProtoReflect.Descriptor instead.
func (*ParseRssResponse) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{1}
}

func (x *ParseRssResponse) GetResponse() isParseRssResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ParseRssResponse) GetRss() *anypb.Any {
	if x != nil {
		if x, ok := x.Response.(*ParseRssResponse_Rss); ok {
			return x.Rss
		}
	}
	return nil
}

func (x *ParseRssResponse) GetError() *ParseError {
	if x != nil {
		if x, ok := x.Response.(*ParseRssResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isParseRssResponse_Response interface {
	isParseRssResponse_Response()
}

type ParseRssResponse_Rss struct {
	Rss *anypb.Any `protobuf:"bytes,1,opt,name=rss,proto3,oneof"`
}

type ParseRssResponse_Error struct {
	Error *ParseError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ParseRssResponse_Rss) isParseRssResponse_Response() {}

func (*ParseRssResponse_Error) isParseRssResponse_Response() {}

type ParseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Xml   []byte                 `protobuf:"bytes,1,opt,name=xml,proto3" json:"xml,omitempty"`
	// validate selects the parser mode (XML's validating vs non-validating
	// processor distinction). When false, only well-formedness is checked and
	// any well-formed document is accepted. When true, the document is validated
	// against its DTD: it must have one and satisfy it.
	Validate      bool `protobuf:"varint,2,opt,name=validate,proto3" json:"validate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_xml_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{2}
}

func (x *ParseRequest) GetXml() []byte {
	if x != nil {
		return x.Xml
	}
	return nil
}

func (x *ParseRequest) GetValidate() bool {
	if x != nil {
		return x.Validate
	}
	return false
}

type ParseError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       Verdict                `protobuf:"varint,1,opt,name=verdict,proto3,enum=xml.Verdict" json:"verdict,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // human-readable detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseError) Reset() {
	*x = ParseError{}
	mi := &file_xml_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseError) ProtoMessage() {}

func (x *ParseError) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseError.ProtoReflect.Descriptor instead.
func (*ParseError) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{3}
}

func (x *ParseError) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *ParseError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ParseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A Document on acceptance, or a ParseError on refusal, never both. There is
	// no point returning a tree for input that is not well-formed or not valid.
	//
	// Types that are valid to be assigned to Response:
	//
	//	*ParseResponse_Document
	//	*ParseResponse_Error
	Response      isParseResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_xml_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{4}
}

func (x *ParseResponse) GetResponse() isParseResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ParseResponse) GetDocument() *Document {
	if x != nil {
		if x, ok := x.Response.(*ParseResponse_Document); ok {
			return x.Document
		}
	}
	return nil
}

func (x *ParseResponse) GetError() *ParseError {
	if x != nil {
		if x, ok := x.Response.(*ParseResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isParseResponse_Response interface {
	isParseResponse_Response()
}

type ParseResponse_Document struct {
	Document *Document `protobuf:"bytes,1,opt,name=document,proto3,oneof"`
}

type ParseResponse_Error struct {
	Error *ParseError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ParseResponse_Document) isParseResponse_Response() {}

func (*ParseResponse_Error) isParseResponse_Response() {}

type CompileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The DTD external subset to compile.
	Dtd []byte `protobuf:"bytes,1,opt,name=dtd,proto3" json:"dtd,omitempty"`
	// Naming options for the emitted descriptor; all optional.
	Package       string `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`                      // proto package (e.g. "rss"); defaults to "lang".
	GoPackage     string `protobuf:"bytes,3,opt,name=go_package,json=goPackage,proto3" json:"go_package,omitempty"` // go_package file option; omitted if empty.
	FileName      string `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`    // FileDescriptorProto.name; "<package>.proto" default.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_xml_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{5}
}

func (x *CompileRequest) GetDtd() []byte {
	if x != nil {
		return x.Dtd
	}
	return nil
}

func (x *CompileRequest) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *CompileRequest) GetGoPackage() string {
	if x != nil {
		return x.GoPackage
	}
	return ""
}

func (x *CompileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type CompileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The compiled schema. It can be linked with protodesc for dynamic use or
	// written out as a .proto / FileDescriptorSet.
	File          *descriptorpb.FileDescriptorProto `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_xml_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xml_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_xml_service_proto_rawDescGZIP(), []int{6}
}

func (x *CompileResponse) GetFile() *descriptorpb.FileDescriptorProto {
	if x != nil {
		return x.File
	}
	return nil
}

var File_xml_service_proto protoreflect.FileDescriptor

const file_xml_service_proto_rawDesc = "" +
	"\n" +
	"\x11xml_service.proto\x12\x03xml\x1a\txml.proto\x1a\x19google/protobuf/any.proto\x1a google/protobuf/descriptor.proto\"#\n" +
	"\x0fParseRssRequest\x12\x10\n" +
	"\x03xml\x18\x01 \x01(\fR\x03xml\"q\n" +
	"\x10ParseRssResponse\x12(\n" +
	"\x03rss\x18\x01 \x01(\v2\x14.google.protobuf.AnyH\x00R\x03rss\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.xml.ParseErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"<\n" +
	"\fParseRequest\x12\x10\n" +
	"\x03xml\x18\x01 \x01(\fR\x03xml\x12\x1a\n" +
	"\bvalidate\x18\x02 \x01(\bR\bvalidate\"L\n" +
	"\n" +
	"ParseError\x12&\n" +
	"\averdict\x18\x01 \x01(\x0e2\f.xml.VerdictR\averdict\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"q\n" +
	"\rParseResponse\x12+\n" +
	"\bdocument\x18\x01 \x01(\v2\r.xml.DocumentH\x00R\bdocument\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.xml.ParseErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"x\n" +
	"\x0eCompileRequest\x12\x10\n" +
	"\x03dtd\x18\x01 \x01(\fR\x03dtd\x12\x18\n" +
	"\apackage\x18\x02 \x01(\tR\apackage\x12\x1d\n" +
	"\n" +
	"go_package\x18\x03 \x01(\tR\tgoPackage\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\"K\n" +
	"\x0fCompileResponse\x128\n" +
	"\x04file\x18\x01 \x01(\v2$.google.protobuf.FileDescriptorProtoR\x04file*Y\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fNOT_WELL_FORMED\x10\x01\x12\v\n" +
	"\aINVALID\x10\x02\x12\x13\n" +
	"\x0fCANNOT_VALIDATE\x10\x032u\n" +
	"\n" +
	"XmlService\x12.\n" +
	"\x05Parse\x12\x11.xml.ParseRequest\x1a\x12.xml.ParseResponse\x127\n" +
	"\bParseRss\x12\x14.xml.ParseRssRequest\x1a\x15.xml.ParseRssResponse2E\n" +
	"\rSchemaService\x124\n" +
	"\aCompile\x12\x13.xml.CompileRequest\x1a\x14.xml.CompileResponseB1Z/github.com/accretional/xmile/proto/pb/xml;xmlpbb\x06proto3"

var (
	file_xml_service_proto_rawDescOnce sync.Once
	file_xml_service_proto_rawDescData []byte
)

func file_xml_service_proto_rawDescGZIP() []byte {
	file_xml_service_proto_rawDescOnce.Do(func() {
		file_xml_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xml_service_proto_rawDesc), len(file_xml_service_proto_rawDesc)))
	})
	return file_xml_service_proto_rawDescData
}

var file_xml_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xml_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_xml_service_proto_goTypes = []any{
	(Verdict)(0),                             // 0: xml.Verdict
	(*ParseRssRequest)(nil),                  // 1: xml.ParseRssRequest
	(*ParseRssResponse)(nil),                 // 2: xml.ParseRssResponse
	(*ParseRequest)(nil),                     // 3: xml.ParseRequest
	(*ParseError)(nil),                       // 4: xml.ParseError
	(*ParseResponse)(nil),                    // 5: xml.ParseResponse
	(*CompileRequest)(nil),                   // 6: xml.CompileRequest
	(*CompileResponse)(nil),                  // 7: xml.CompileResponse
	(*anypb.Any)(nil),                        // 8: google.protobuf.Any
	(*Document)(nil),                         // 9: xml.Document
	(*descriptorpb.FileDescriptorProto)(nil), // 10: google.protobuf.FileDescriptorProto
}
var file_xml_service_proto_depIdxs = []int32{
	8,  // 0: xml.ParseRssResponse.rss:type_name -> google.protobuf.Any
	4,  // 1: xml.ParseRssResponse.error:type_name -> xml.ParseError
	0,  // 2: xml.ParseError.verdict:type_name -> xml.Verdict
	9,  // 3: xml.ParseResponse.document:type_name -> xml.Document
	4,  // 4: xml.ParseResponse.error:type_name -> xml.ParseError
	10, // 5: xml.CompileResponse.file:type_name -> google.protobuf.FileDescriptorProto
	3,  // 6: xml.XmlService.Parse:input_type -> xml.ParseRequest
	1,  // 7: xml.XmlService.ParseRss:input_type -> xml.ParseRssRequest
	6,  // 8: xml.SchemaService.Compile:input_type -> xml.CompileRequest
	5,  // 9: xml.XmlService.Parse:output_type -> xml.ParseResponse
	2,  // 10: xml.XmlService.ParseRss:output_type -> xml.ParseRssResponse
	7,  // 11: xml.SchemaService.Compile:output_type -> xml.CompileResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_xml_service_proto_init() }
func file_xml_service_proto_init() {
	if File_xml_service_proto != nil {
		return
	}
	file_xml_proto_init()
	file_xml_service_proto_msgTypes[1].OneofWrappers = []any{
		(*ParseRssResponse_Rss)(nil),
		(*ParseRssResponse_Error)(nil),
	}
	file_xml_service_proto_msgTypes[4].OneofWrappers = []any{
		(*ParseResponse_Document)(nil),
		(*ParseResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xml_service_proto_rawDesc), len(file_xml_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_xml_service_proto_goTypes,
		DependencyIndexes: file_xml_service_proto_depIdxs,
		EnumInfos:         file_xml_service_proto_enumTypes,
		MessageInfos:      file_xml_service_proto_msgTypes,
	}.Build()
	File_xml_service_proto = out.File
	file_xml_service_proto_goTypes = nil
	file_xml_service_proto_depIdxs = nil
}
