package service

// dtd_roundtrip_test.go — a robust gate for DOCTYPE round-trip preservation.
//
// The invariant under test (project.go + generate.go): the projector captures
// the whole DOCTYPE body verbatim in Xml.Doctype (the dtd_text span between
// "<!DOCTYPE" and its matching ">"), and Generate re-emits "<!DOCTYPE" + body +
// ">". So a document must satisfy BOTH:
//
//	(1) Generate(parse(b)) reproduces the DOCTYPE verbatim, and
//	(2) parse(Generate(parse(b))) == parse(b)   (at the canonical infoset).
//
// Every subtest asserts both. Equality is at the canonical infoset — the same
// reduction the corpus generate gate uses (testing/main.go): the encoding decl is
// cleared (Generate always emits UTF-8) and adjacent character-data runs are
// coalesced (a general-entity reference expands into content as several text
// items, which the infoset defines as one run). The DOCTYPE body itself is NOT
// canonicalized away: Doctype.Name is compared verbatim by proto.Equal, so (2)
// already pins the DOCTYPE at the AST level; (1) additionally pins the bytes.
//
// The suite covers the internal subset (ELEMENT/ATTLIST/ENTITY/NOTATION, mixed
// content, comments and PIs inside the subset), external ids (SYSTEM, PUBLIC,
// XHTML 1.0 Strict, and SYSTEM + internal subset), entity expansion in content,
// whitespace-only and no-subset bodies, a '>' hidden in a quoted literal, real
// well-known public doctypes (SVG/DocBook/plist/RSS), a no-DOCTYPE negative
// sanity, and a loop over every DOCTYPE-bearing document in the W3C corpus.

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"google.golang.org/protobuf/proto"

	xmlpb "github.com/accretional/xmile/proto/pb/xml"
)

// canonDTD reduces an Xml AST to the canonical infoset form used for round-trip
// comparison (mirrors testing/main.go's canonicalXML): clear the encoding
// declaration and coalesce adjacent character-data runs. Doctype is left intact
// so the verbatim body participates in proto.Equal.
func canonDTD(x *xmlpb.Xml) *xmlpb.Xml {
	c, _ := proto.Clone(x).(*xmlpb.Xml)
	if d := c.GetXmlDecl(); d != nil {
		d.Encoding = ""
	}
	coalesceDTD(c.GetRoot())
	return c
}

func coalesceDTD(t *xmlpb.Tag) {
	if t == nil {
		return
	}
	var out []*xmlpb.ContentItem
	for _, ci := range t.GetContents() {
		switch it := ci.GetItem().(type) {
		case *xmlpb.ContentItem_Text:
			if n := len(out); n > 0 {
				if prev, ok := out[n-1].GetItem().(*xmlpb.ContentItem_Text); ok {
					prev.Text += it.Text
					continue
				}
			}
			out = append(out, ci)
		case *xmlpb.ContentItem_Child:
			coalesceDTD(it.Child)
			out = append(out, ci)
		default:
			out = append(out, ci)
		}
	}
	final := out[:0]
	for _, ci := range out {
		if txt, ok := ci.GetItem().(*xmlpb.ContentItem_Text); ok && txt.Text == "" {
			continue
		}
		final = append(final, ci)
	}
	t.Contents = final
}

// assertDTDRoundTrip is the shared body: parse src, require a DOCTYPE, Generate,
// assert the DOCTYPE is reproduced verbatim in the bytes, re-parse, and assert
// the canonical AST is unchanged. Returns the generated bytes for extra checks.
func assertDTDRoundTrip(t *testing.T, p *Parser, src, wantDoctype string) string {
	t.Helper()
	x1, err := p.Parse(src, false)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if x1.GetDoctype() == nil {
		t.Fatalf("Doctype should be populated from the parsed DOCTYPE; src=%q", src)
	}
	out, err := Generate(x1)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	gen := string(out)

	// (1a) The generated bytes reproduce the exact DOCTYPE this test expects.
	if wantDoctype != "" && !strings.Contains(gen, wantDoctype) {
		t.Errorf("DOCTYPE not reproduced verbatim\n  want substring: %q\n  got output:     %q", wantDoctype, gen)
	}
	// (1b) And that string is exactly what Generate builds from the captured body
	// ("<!DOCTYPE" + verbatim body + ">"): guards against the parser capturing a
	// wrong span that happens to still contain wantDoctype.
	rebuilt := "<!DOCTYPE" + x1.GetDoctype().GetName() + ">"
	if !strings.Contains(gen, rebuilt) {
		t.Errorf("Generate did not re-emit the captured DOCTYPE body\n  captured: %q\n  output:   %q", rebuilt, gen)
	}
	if wantDoctype != "" && rebuilt != wantDoctype {
		t.Errorf("captured DOCTYPE body differs from expected\n  captured: %q\n  expected: %q", rebuilt, wantDoctype)
	}

	// (2) Full round-trip: the re-parsed AST equals the first at the canonical infoset.
	x2, err := p.Parse(gen, false)
	if err != nil {
		t.Fatalf("re-parse of generated %q: %v", gen, err)
	}
	if !proto.Equal(canonDTD(x1), canonDTD(x2)) {
		t.Errorf("round-trip AST differs (DOCTYPE or element tree)\n  generated: %q", gen)
	}
	return gen
}

func TestDTDRoundTrip(t *testing.T) {
	p, err := Default()
	if err != nil {
		t.Fatalf("Default: %v", err)
	}

	cases := []struct {
		name, src, wantDoctype string
		// wantContains / wantNotContains assert on the generated bytes: e.g. an
		// entity expanded in content (present) and its "&name;" reference (gone).
		wantContains    []string
		wantNotContains []string
	}{
		// ---- internal subset ----
		{
			name:        "internal subset: ELEMENT + ATTLIST (default, #REQUIRED, enumeration)",
			src:         `<?xml version="1.0"?><!DOCTYPE doc [<!ELEMENT doc (#PCDATA)><!ATTLIST doc id ID #REQUIRED lang CDATA "en" kind (draft|final) "draft">]><doc id="d1">body</doc>`,
			wantDoctype: `<!DOCTYPE doc [<!ELEMENT doc (#PCDATA)><!ATTLIST doc id ID #REQUIRED lang CDATA "en" kind (draft|final) "draft">]>`,
		},
		{
			name:        "internal subset: mixed content model + EMPTY + child ELEMENT",
			src:         `<!DOCTYPE doc [<!ELEMENT doc (#PCDATA|b|i)*><!ELEMENT b EMPTY><!ELEMENT i (#PCDATA)>]><doc>text<b/>more<i>x</i></doc>`,
			wantDoctype: `<!DOCTYPE doc [<!ELEMENT doc (#PCDATA|b|i)*><!ELEMENT b EMPTY><!ELEMENT i (#PCDATA)>]>`,
		},
		{
			name:            "internal subset: general + parameter ENTITY declarations",
			src:             `<!DOCTYPE doc [<!ENTITY % pe "<!ELEMENT doc (#PCDATA)>"> %pe; <!ENTITY ge "resolved">]><doc>&ge;</doc>`,
			wantDoctype:     `<!DOCTYPE doc [<!ENTITY % pe "<!ELEMENT doc (#PCDATA)>"> %pe; <!ENTITY ge "resolved">]>`,
			wantContains:    []string{"resolved"},
			wantNotContains: []string{"&ge;"},
		},
		{
			name:        "internal subset: NOTATION (PUBLIC + SYSTEM) + ATTLIST NOTATION enumeration",
			src:         `<!DOCTYPE doc [<!ELEMENT doc EMPTY><!NOTATION gif PUBLIC "-//IETF//NOTATION GIF//EN"><!NOTATION png SYSTEM "png.exe"><!ATTLIST doc pic NOTATION (gif|png) #IMPLIED>]><doc/>`,
			wantDoctype: `<!DOCTYPE doc [<!ELEMENT doc EMPTY><!NOTATION gif PUBLIC "-//IETF//NOTATION GIF//EN"><!NOTATION png SYSTEM "png.exe"><!ATTLIST doc pic NOTATION (gif|png) #IMPLIED>]>`,
		},
		{
			name:        "internal subset: comments and PIs inside the subset",
			src:         `<!DOCTYPE doc [<!-- a declaration comment --><?build target="dtd"?><!ELEMENT doc EMPTY>]><doc/>`,
			wantDoctype: `<!DOCTYPE doc [<!-- a declaration comment --><?build target="dtd"?><!ELEMENT doc EMPTY>]>`,
		},

		// ---- external ids ----
		{
			name:        "external id: SYSTEM only",
			src:         `<!DOCTYPE root SYSTEM "root.dtd"><root>hi</root>`,
			wantDoctype: `<!DOCTYPE root SYSTEM "root.dtd">`,
		},
		{
			name:        "external id: PUBLIC + system literal",
			src:         `<!DOCTYPE root PUBLIC "-//Example//DTD Test v1//EN" "http://example.com/test.dtd"><root/>`,
			wantDoctype: `<!DOCTYPE root PUBLIC "-//Example//DTD Test v1//EN" "http://example.com/test.dtd">`,
		},
		{
			name:        "external id: PUBLIC XHTML 1.0 Strict",
			src:         `<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>t</title></head><body><p>hi</p></body></html>`,
			wantDoctype: `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">`,
		},
		{
			name:            "external id: SYSTEM with an internal subset combined",
			src:             `<!DOCTYPE root SYSTEM "root.dtd" [<!ENTITY x "expanded">]><root>&x;</root>`,
			wantDoctype:     `<!DOCTYPE root SYSTEM "root.dtd" [<!ENTITY x "expanded">]>`,
			wantContains:    []string{"expanded"},
			wantNotContains: []string{"&x;"},
		},

		// ---- entity expansion in content ----
		{
			name:            "entities: text general entity declared in subset and used in content",
			src:             `<!DOCTYPE doc [<!ELEMENT doc (#PCDATA)><!ENTITY logo "ACME Corp">]><doc>Made by &logo; today</doc>`,
			wantDoctype:     `<!DOCTYPE doc [<!ELEMENT doc (#PCDATA)><!ENTITY logo "ACME Corp">]>`,
			wantContains:    []string{"Made by ACME Corp today"},
			wantNotContains: []string{"&logo;"},
		},
		{
			name:         "entities: general entity expanding to markup used in content",
			src:          `<!DOCTYPE doc [<!ELEMENT doc (#PCDATA|em)*><!ELEMENT em (#PCDATA)><!ENTITY frag "<em>bold</em>">]><doc>a&frag;b</doc>`,
			wantDoctype:  `<!DOCTYPE doc [<!ELEMENT doc (#PCDATA|em)*><!ELEMENT em (#PCDATA)><!ENTITY frag "<em>bold</em>">]>`,
			wantContains: []string{"<em>bold</em>"},
		},
		{
			// A parameter entity referenced in the internal subset as a declaration
			// separator (the only place a PE reference is well-formed there — it must
			// not occur inside a markup declaration in the internal subset). Its
			// replacement contributes whole markup declarations.
			name:        "entities: parameter entity referenced in the internal subset",
			src:         `<!DOCTYPE doc [<!ENTITY % elems "<!ELEMENT doc (b)><!ELEMENT b EMPTY>"> %elems;]><doc><b/></doc>`,
			wantDoctype: `<!DOCTYPE doc [<!ENTITY % elems "<!ELEMENT doc (b)><!ELEMENT b EMPTY>"> %elems;]>`,
		},

		// ---- degenerate bodies ----
		{
			name:        "no internal subset (just <!DOCTYPE root>)",
			src:         `<!DOCTYPE root><root>x</root>`,
			wantDoctype: `<!DOCTYPE root>`,
		},
		{
			name:        "DOCTYPE root followed by only whitespace",
			src:         "<!DOCTYPE root   ><root/>",
			wantDoctype: "<!DOCTYPE root   >",
		},
		{
			name:        "DOCTYPE with an empty whitespace-only internal subset",
			src:         `<!DOCTYPE root [   ]><root/>`,
			wantDoctype: `<!DOCTYPE root [   ]>`,
		},
		{
			name:        "DOCTYPE body spanning a newline",
			src:         "<!DOCTYPE root\n\t[<!ELEMENT root EMPTY>]\n><root/>",
			wantDoctype: "<!DOCTYPE root\n\t[<!ELEMENT root EMPTY>]\n>",
		},

		// ---- the ">" / markup-looking edge ----
		{
			name:        "edge: '>' and markup-looking text hidden inside quoted entity literals",
			src:         `<!DOCTYPE doc [<!ELEMENT doc EMPTY><!ENTITY gtish "a > b >= c"><!ENTITY tagish "<p>not a real element</p>">]><doc/>`,
			wantDoctype: `<!DOCTYPE doc [<!ELEMENT doc EMPTY><!ENTITY gtish "a > b >= c"><!ENTITY tagish "<p>not a real element</p>">]>`,
		},
		{
			name:        "edge: system literal containing '>' and '['",
			src:         `<!DOCTYPE doc SYSTEM "urn:x?q=a>b&amp;r=[1]"><doc/>`,
			wantDoctype: `<!DOCTYPE doc SYSTEM "urn:x?q=a>b&amp;r=[1]">`,
		},

		// ---- realistic well-known public doctypes (hand-authored fixtures) ----
		{
			name:        "real: SVG 1.1",
			src:         `<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect x="0" y="0" width="10" height="10"/></svg>`,
			wantDoctype: `<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">`,
		},
		{
			name:        "real: DocBook XML V4.5",
			src:         `<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE article PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"><article><title>Doc</title><para>Text.</para></article>`,
			wantDoctype: `<!DOCTYPE article PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd">`,
		},
		{
			name:        "real: Apple plist 1.0",
			src:         `<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>Name</key><string>Value</string></dict></plist>`,
			wantDoctype: `<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`,
		},
		{
			name:        "real: RSS 0.91 (Netscape)",
			src:         `<?xml version="1.0"?><!DOCTYPE rss PUBLIC "-//Netscape Communications//DTD RSS 0.91//EN" "http://my.netscape.com/publish/formats/rss-0.91.dtd"><rss version="0.91"><channel><title>Feed</title><link>http://example.com</link><description>d</description></channel></rss>`,
			wantDoctype: `<!DOCTYPE rss PUBLIC "-//Netscape Communications//DTD RSS 0.91//EN" "http://my.netscape.com/publish/formats/rss-0.91.dtd">`,
		},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			gen := assertDTDRoundTrip(t, p, c.src, c.wantDoctype)
			for _, s := range c.wantContains {
				if !strings.Contains(gen, s) {
					t.Errorf("generated output missing expected content %q\n  got: %q", s, gen)
				}
			}
			for _, s := range c.wantNotContains {
				if strings.Contains(gen, s) {
					t.Errorf("generated output should not contain %q (entity should have expanded)\n  got: %q", s, gen)
				}
			}
		})
	}
}

// A document with no DOCTYPE must generate with no DOCTYPE at all.
func TestDTDRoundTrip_NoDoctype(t *testing.T) {
	p, err := Default()
	if err != nil {
		t.Fatalf("Default: %v", err)
	}
	for _, src := range []string{
		`<a>no doctype here</a>`,
		`<?xml version="1.0"?><root><child/></root>`,
	} {
		x, err := p.Parse(src, false)
		if err != nil {
			t.Fatalf("parse %q: %v", src, err)
		}
		if x.GetDoctype() != nil {
			t.Errorf("expected nil Doctype for %q, got %q", src, x.GetDoctype().GetName())
		}
		out, err := Generate(x)
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}
		if strings.Contains(string(out), "<!DOCTYPE") {
			t.Errorf("output for a no-DOCTYPE document must not contain <!DOCTYPE; got %q", out)
		}
		x2, err := p.Parse(string(out), false)
		if err != nil {
			t.Fatalf("re-parse: %v", err)
		}
		if !proto.Equal(canonDTD(x), canonDTD(x2)) {
			t.Errorf("no-DOCTYPE round-trip AST differs\n  generated: %q", out)
		}
	}
}

// normalizedForParse reconstructs the source string the parser actually parses
// (parser.go's parse: encoding-normalize, decode declared encoding, line-end-
// normalize). The captured dtd_text is a verbatim substring of this, so the
// generated DOCTYPE must appear here — a fidelity check against the real source,
// not against what Generate itself produced.
func normalizedForParse(b []byte) string {
	s := normalizeEncoding(string(b))
	s = decodeDeclaredEncoding(s)
	return normalizeLineEnds(s, detectVersion(s))
}

// TestDTDRoundTrip_Corpus loops every DOCTYPE-bearing document in the cached W3C
// conformance corpus and asserts each round-trips with its DOCTYPE reproduced
// verbatim — validation against real documents. A "DOCTYPE-bearing" document is
// one that parses to a non-nil Xml.Doctype (this correctly includes UTF-16/Latin-1
// sources, whose "<!DOCTYPE" a raw byte scan would miss). Not-well-formed inputs
// (most of not-wf/) have nothing to generate and are skipped.
func TestDTDRoundTrip_Corpus(t *testing.T) {
	p, err := Default()
	if err != nil {
		t.Fatalf("Default: %v", err)
	}
	srv, err := NewDocumentsServer()
	if err != nil {
		t.Fatalf("NewDocumentsServer: %v", err)
	}
	ctx := context.Background()

	base := filepath.Join("..", "testing", "corpus", "xml")
	if _, err := os.Stat(base); err != nil {
		t.Skipf("corpus not present at %s (run: go run ./testing fetch); relying on embedded fixtures", base)
	}

	var files []string
	for _, verdict := range []string{"valid", "invalid", "not-wf"} {
		matches, _ := filepath.Glob(filepath.Join(base, verdict, "*.xml"))
		files = append(files, matches...)
	}
	if len(files) == 0 {
		t.Skipf("no corpus files under %s; relying on embedded fixtures", base)
	}

	scanned, withDoctype, passed := 0, 0, 0
	for _, fp := range files {
		b, err := os.ReadFile(fp)
		if err != nil {
			continue
		}
		scanned++
		x1, perr := p.Parse(string(b), false)
		if perr != nil {
			continue // not-wf / rejected: nothing to generate
		}
		dt := x1.GetDoctype()
		if dt == nil {
			continue // no DOCTYPE in this document
		}
		withDoctype++
		name := filepath.Base(fp)
		want := "<!DOCTYPE" + dt.GetName() + ">"

		// The captured DOCTYPE must be a verbatim substring of the real (decoded,
		// line-end-normalized) source. If not, the projector captured the wrong
		// span — a real bug.
		if src := normalizedForParse(b); !strings.Contains(src, want) {
			t.Errorf("[%s] captured DOCTYPE is not a verbatim substring of the source\n  captured: %q", name, want)
			continue
		}

		g, err := srv.Generate(ctx, &xmlpb.GenerateRequest{Document: x1})
		if err != nil || g.GetError() != nil {
			t.Errorf("[%s] Generate failed: %v %s", name, err, g.GetError().GetReason())
			continue
		}
		out := string(g.GetSource())
		if !strings.Contains(out, want) {
			t.Errorf("[%s] DOCTYPE not reproduced verbatim in generated output\n  want: %q", name, want)
			continue
		}
		x2, perr := p.Parse(out, false)
		if perr != nil {
			t.Errorf("[%s] generated document does not re-parse: %v", name, perr)
			continue
		}
		if !proto.Equal(canonDTD(x1), canonDTD(x2)) {
			t.Errorf("[%s] round-trip AST differs (DOCTYPE or element tree)", name)
			continue
		}
		passed++
	}

	t.Logf("corpus DOCTYPE round-trip: scanned %d files, %d parsed with a DOCTYPE, %d/%d round-tripped verbatim",
		scanned, withDoctype, passed, withDoctype)
	if withDoctype == 0 {
		t.Skip("no DOCTYPE-bearing documents parsed from the corpus; relying on embedded fixtures")
	}
	if passed != withDoctype {
		t.Errorf("%d of %d DOCTYPE documents did NOT round-trip verbatim (see failures above)", withDoctype-passed, withDoctype)
	}
}
