// Code generated by genproto. DO NOT EDIT.

package dtdpb

// FieldSeparator maps "parentFQN.fieldName" to the literal that
// CollapseCommaList dropped when rewriting "X (SEP X)*" to a repeated field.
var FieldSeparator = map[string]string{
}
