package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

// genLex compiles a lang/*.lex spec into a generated Go table
// (proto/pb/<pkg>/lexical.go) of lex.Matcher values. The runtime parser
// reads this table through package lex; no lexical data lives in Go.
func genLex(specPath, outPath, pkg string) error {
	f, err := os.Open(specPath)
	if err != nil {
		return fmt.Errorf("open %s: %w", specPath, err)
	}
	defer f.Close()

	type entry struct{ name, body string }
	var entries []entry

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			return fmt.Errorf("%s: malformed line %q", specPath, line)
		}
		name, kind := fields[0], fields[1]
		args := fields[2:]

		var body string
		switch kind {
		case "run":
			body = fmt.Sprintf("Kind: %q, Ranges: %s", "run", goRanges(args))
		case "name":
			slash := indexOf(args, "/")
			if slash < 0 {
				return fmt.Errorf("%s: name %q needs a '/' separator", specPath, name)
			}
			body = fmt.Sprintf("Kind: %q, Ranges: %s, Rest: %s",
				"name", goRanges(args[:slash]), goRanges(args[slash+1:]))
		case "except":
			body = fmt.Sprintf("Kind: %q, Stops: %q", "except", hexBytes(args))
		case "until":
			if len(args) != 1 {
				return fmt.Errorf("%s: until %q needs exactly one delimiter", specPath, name)
			}
			body = fmt.Sprintf("Kind: %q, Delim: %q", "until", args[0])
		case "balanced":
			body = fmt.Sprintf("Kind: %q", "balanced")
		default:
			return fmt.Errorf("%s: unknown lex kind %q", specPath, kind)
		}
		entries = append(entries, entry{name, body})
	}
	if err := sc.Err(); err != nil {
		return err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].name < entries[j].name })

	var b strings.Builder
	b.WriteString("// Code generated by genproto. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import \"github.com/accretional/xmile/lex\"\n\n")
	b.WriteString("// Lexical maps each token-matcher name to its lexical rule.\n")
	b.WriteString("var Lexical = map[string]lex.Matcher{\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t%q: {%s},\n", e.name, e.body)
	}
	b.WriteString("}\n")
	return writeFile(outPath, b.String())
}

// goRanges renders hex range tokens ("41-5A", "5F") as a []lex.Range literal.
func goRanges(toks []string) string {
	parts := make([]string, 0, len(toks))
	for _, t := range toks {
		lo, hi := parseRange(t)
		parts = append(parts, fmt.Sprintf("{Lo: 0x%X, Hi: 0x%X}", lo, hi))
	}
	return "[]lex.Range{" + strings.Join(parts, ", ") + "}"
}

func parseRange(t string) (rune, rune) {
	if i := strings.IndexByte(t, '-'); i > 0 {
		lo, _ := strconv.ParseInt(t[:i], 16, 32)
		hi, _ := strconv.ParseInt(t[i+1:], 16, 32)
		return rune(lo), rune(hi)
	}
	v, _ := strconv.ParseInt(t, 16, 32)
	return rune(v), rune(v)
}

// hexBytes turns hex codepoint tokens into a literal byte string (used for
// `except` stop sets, which are always ASCII).
func hexBytes(toks []string) string {
	var sb strings.Builder
	for _, t := range toks {
		v, _ := strconv.ParseInt(t, 16, 32)
		sb.WriteByte(byte(v))
	}
	return sb.String()
}

func indexOf(s []string, v string) int {
	for i, x := range s {
		if x == v {
			return i
		}
	}
	return -1
}
