// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rss.proto

package rsspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rss struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Channel       *Channel               `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rss) Reset() {
	*x = Rss{}
	mi := &file_rss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rss) ProtoMessage() {}

func (x *Rss) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rss.ProtoReflect.Descriptor instead.
func (*Rss) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{0}
}

func (x *Rss) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Rss) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alt1          []*Channel_Alt1        `protobuf:"bytes,1,rep,name=alt1,proto3" json:"alt1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_rss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{1}
}

func (x *Channel) GetAlt1() []*Channel_Alt1 {
	if x != nil {
		return x.Alt1
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alt1          []*Item_Alt1           `protobuf:"bytes,1,rep,name=alt1,proto3" json:"alt1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_rss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetAlt1() []*Item_Alt1 {
	if x != nil {
		return x.Alt1
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alt1          []*Image_Alt1          `protobuf:"bytes,1,rep,name=alt1,proto3" json:"alt1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_rss_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{3}
}

func (x *Image) GetAlt1() []*Image_Alt1 {
	if x != nil {
		return x.Alt1
	}
	return nil
}

type TextInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *Title                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   *Description           `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Name          *Name                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Link          *Link                  `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextInput) Reset() {
	*x = TextInput{}
	mi := &file_rss_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextInput) ProtoMessage() {}

func (x *TextInput) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextInput.ProtoReflect.Descriptor instead.
func (*TextInput) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{4}
}

func (x *TextInput) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *TextInput) GetDescription() *Description {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *TextInput) GetName() *Name {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *TextInput) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type Cloud struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Domain            string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Port              string                 `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Path              string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	RegisterProcedure string                 `protobuf:"bytes,4,opt,name=register_procedure,json=registerProcedure,proto3" json:"register_procedure,omitempty"`
	Protocol          string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Cloud) Reset() {
	*x = Cloud{}
	mi := &file_rss_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cloud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cloud) ProtoMessage() {}

func (x *Cloud) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cloud.ProtoReflect.Descriptor instead.
func (*Cloud) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{5}
}

func (x *Cloud) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Cloud) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Cloud) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Cloud) GetRegisterProcedure() string {
	if x != nil {
		return x.RegisterProcedure
	}
	return ""
}

func (x *Cloud) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type Enclosure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Length        string                 `protobuf:"bytes,2,opt,name=length,proto3" json:"length,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enclosure) Reset() {
	*x = Enclosure{}
	mi := &file_rss_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enclosure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enclosure) ProtoMessage() {}

func (x *Enclosure) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enclosure.ProtoReflect.Descriptor instead.
func (*Enclosure) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{6}
}

func (x *Enclosure) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Enclosure) GetLength() string {
	if x != nil {
		return x.Length
	}
	return ""
}

func (x *Enclosure) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_rss_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{7}
}

func (x *Source) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Source) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_rss_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{8}
}

func (x *Category) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Category) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Guid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPermaLink   string                 `protobuf:"bytes,1,opt,name=is_perma_link,json=isPermaLink,proto3" json:"is_perma_link,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Guid) Reset() {
	*x = Guid{}
	mi := &file_rss_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guid) ProtoMessage() {}

func (x *Guid) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guid.ProtoReflect.Descriptor instead.
func (*Guid) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{9}
}

func (x *Guid) GetIsPermaLink() string {
	if x != nil {
		return x.IsPermaLink
	}
	return ""
}

func (x *Guid) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SkipHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hour          []*Hour                `protobuf:"bytes,1,rep,name=hour,proto3" json:"hour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipHours) Reset() {
	*x = SkipHours{}
	mi := &file_rss_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipHours) ProtoMessage() {}

func (x *SkipHours) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipHours.ProtoReflect.Descriptor instead.
func (*SkipHours) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{10}
}

func (x *SkipHours) GetHour() []*Hour {
	if x != nil {
		return x.Hour
	}
	return nil
}

type SkipDays struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           []*Day                 `protobuf:"bytes,1,rep,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipDays) Reset() {
	*x = SkipDays{}
	mi := &file_rss_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipDays) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipDays) ProtoMessage() {}

func (x *SkipDays) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipDays.ProtoReflect.Descriptor instead.
func (*SkipDays) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{11}
}

func (x *SkipDays) GetDay() []*Day {
	if x != nil {
		return x.Day
	}
	return nil
}

type Title struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_rss_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{12}
}

func (x *Title) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_rss_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{13}
}

func (x *Link) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Description struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Description) Reset() {
	*x = Description{}
	mi := &file_rss_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Description) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Description) ProtoMessage() {}

func (x *Description) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Description.ProtoReflect.Descriptor instead.
func (*Description) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{14}
}

func (x *Description) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Language struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Language) Reset() {
	*x = Language{}
	mi := &file_rss_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{15}
}

func (x *Language) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Copyright struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Copyright) Reset() {
	*x = Copyright{}
	mi := &file_rss_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Copyright) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Copyright) ProtoMessage() {}

func (x *Copyright) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Copyright.ProtoReflect.Descriptor instead.
func (*Copyright) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{16}
}

func (x *Copyright) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ManagingEditor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagingEditor) Reset() {
	*x = ManagingEditor{}
	mi := &file_rss_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagingEditor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagingEditor) ProtoMessage() {}

func (x *ManagingEditor) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagingEditor.ProtoReflect.Descriptor instead.
func (*ManagingEditor) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{17}
}

func (x *ManagingEditor) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type WebMaster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebMaster) Reset() {
	*x = WebMaster{}
	mi := &file_rss_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebMaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebMaster) ProtoMessage() {}

func (x *WebMaster) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebMaster.ProtoReflect.Descriptor instead.
func (*WebMaster) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{18}
}

func (x *WebMaster) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PubDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubDate) Reset() {
	*x = PubDate{}
	mi := &file_rss_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubDate) ProtoMessage() {}

func (x *PubDate) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubDate.ProtoReflect.Descriptor instead.
func (*PubDate) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{19}
}

func (x *PubDate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LastBuildDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastBuildDate) Reset() {
	*x = LastBuildDate{}
	mi := &file_rss_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastBuildDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastBuildDate) ProtoMessage() {}

func (x *LastBuildDate) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastBuildDate.ProtoReflect.Descriptor instead.
func (*LastBuildDate) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{20}
}

func (x *LastBuildDate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Generator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generator) Reset() {
	*x = Generator{}
	mi := &file_rss_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generator) ProtoMessage() {}

func (x *Generator) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generator.ProtoReflect.Descriptor instead.
func (*Generator) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{21}
}

func (x *Generator) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Docs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Docs) Reset() {
	*x = Docs{}
	mi := &file_rss_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Docs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Docs) ProtoMessage() {}

func (x *Docs) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Docs.ProtoReflect.Descriptor instead.
func (*Docs) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{22}
}

func (x *Docs) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Ttl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ttl) Reset() {
	*x = Ttl{}
	mi := &file_rss_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ttl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ttl) ProtoMessage() {}

func (x *Ttl) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ttl.ProtoReflect.Descriptor instead.
func (*Ttl) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{23}
}

func (x *Ttl) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Rating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rating) Reset() {
	*x = Rating{}
	mi := &file_rss_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{24}
}

func (x *Rating) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Url struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Url) Reset() {
	*x = Url{}
	mi := &file_rss_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{25}
}

func (x *Url) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Width struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Width) Reset() {
	*x = Width{}
	mi := &file_rss_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Width) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Width) ProtoMessage() {}

func (x *Width) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Width.ProtoReflect.Descriptor instead.
func (*Width) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{26}
}

func (x *Width) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Height struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Height) Reset() {
	*x = Height{}
	mi := &file_rss_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Height) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Height) ProtoMessage() {}

func (x *Height) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Height.ProtoReflect.Descriptor instead.
func (*Height) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{27}
}

func (x *Height) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Name struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Name) Reset() {
	*x = Name{}
	mi := &file_rss_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{28}
}

func (x *Name) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_rss_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{29}
}

func (x *Author) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Comments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comments) Reset() {
	*x = Comments{}
	mi := &file_rss_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comments) ProtoMessage() {}

func (x *Comments) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comments.ProtoReflect.Descriptor instead.
func (*Comments) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{30}
}

func (x *Comments) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Hour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hour) Reset() {
	*x = Hour{}
	mi := &file_rss_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hour) ProtoMessage() {}

func (x *Hour) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hour.ProtoReflect.Descriptor instead.
func (*Hour) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{31}
}

func (x *Hour) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Day struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Day) Reset() {
	*x = Day{}
	mi := &file_rss_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Day) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Day) ProtoMessage() {}

func (x *Day) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Day.ProtoReflect.Descriptor instead.
func (*Day) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{32}
}

func (x *Day) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Channel_Alt1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Channel_Alt1_Title
	//	*Channel_Alt1_Link
	//	*Channel_Alt1_Description
	//	*Channel_Alt1_Language
	//	*Channel_Alt1_Copyright
	//	*Channel_Alt1_ManagingEditor
	//	*Channel_Alt1_WebMaster
	//	*Channel_Alt1_PubDate
	//	*Channel_Alt1_LastBuildDate
	//	*Channel_Alt1_Generator
	//	*Channel_Alt1_Docs
	//	*Channel_Alt1_Cloud
	//	*Channel_Alt1_Ttl
	//	*Channel_Alt1_Image
	//	*Channel_Alt1_Rating
	//	*Channel_Alt1_TextInput
	//	*Channel_Alt1_SkipHours
	//	*Channel_Alt1_SkipDays
	//	*Channel_Alt1_Category
	//	*Channel_Alt1_Item
	Value         isChannel_Alt1_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel_Alt1) Reset() {
	*x = Channel_Alt1{}
	mi := &file_rss_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel_Alt1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel_Alt1) ProtoMessage() {}

func (x *Channel_Alt1) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel_Alt1.ProtoReflect.Descriptor instead.
func (*Channel_Alt1) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Channel_Alt1) GetValue() isChannel_Alt1_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Channel_Alt1) GetTitle() *Title {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_Title); ok {
			return x.Title
		}
	}
	return nil
}

func (x *Channel_Alt1) GetLink() *Link {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_Link); ok {
			return x.Link
		}
	}
	return nil
}

func (x *Channel_Alt1) GetDescription() *Description {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_Description); ok {
			return x.Description
		}
	}
	return nil
}

func (x *Channel_Alt1) GetLanguage() *Language {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_Language); ok {
			return x.Language
		}
	}
	return nil
}

func (x *Channel_Alt1) GetCopyright() *Copyright {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_Copyright); ok {
			return x.Copyright
		}
	}
	return nil
}

func (x *Channel_Alt1) GetManagingEditor() *ManagingEditor {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_ManagingEditor); ok {
			return x.ManagingEditor
		}
	}
	return nil
}

func (x *Channel_Alt1) GetWebMaster() *WebMaster {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_WebMaster); ok {
			return x.WebMaster
		}
	}
	return nil
}

func (x *Channel_Alt1) GetPubDate() *PubDate {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_PubDate); ok {
			return x.PubDate
		}
	}
	return nil
}

func (x *Channel_Alt1) GetLastBuildDate() *LastBuildDate {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_LastBuildDate); ok {
			return x.LastBuildDate
		}
	}
	return nil
}

func (x *Channel_Alt1) GetGenerator() *Generator {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_Generator); ok {
			return x.Generator
		}
	}
	return nil
}

func (x *Channel_Alt1) GetDocs() *Docs {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_Docs); ok {
			return x.Docs
		}
	}
	return nil
}

func (x *Channel_Alt1) GetCloud() *Cloud {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_Cloud); ok {
			return x.Cloud
		}
	}
	return nil
}

func (x *Channel_Alt1) GetTtl() *Ttl {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_Ttl); ok {
			return x.Ttl
		}
	}
	return nil
}

func (x *Channel_Alt1) GetImage() *Image {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *Channel_Alt1) GetRating() *Rating {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_Rating); ok {
			return x.Rating
		}
	}
	return nil
}

func (x *Channel_Alt1) GetTextInput() *TextInput {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_TextInput); ok {
			return x.TextInput
		}
	}
	return nil
}

func (x *Channel_Alt1) GetSkipHours() *SkipHours {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_SkipHours); ok {
			return x.SkipHours
		}
	}
	return nil
}

func (x *Channel_Alt1) GetSkipDays() *SkipDays {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_SkipDays); ok {
			return x.SkipDays
		}
	}
	return nil
}

func (x *Channel_Alt1) GetCategory() *Category {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_Category); ok {
			return x.Category
		}
	}
	return nil
}

func (x *Channel_Alt1) GetItem() *Item {
	if x != nil {
		if x, ok := x.Value.(*Channel_Alt1_Item); ok {
			return x.Item
		}
	}
	return nil
}

type isChannel_Alt1_Value interface {
	isChannel_Alt1_Value()
}

type Channel_Alt1_Title struct {
	Title *Title `protobuf:"bytes,1,opt,name=title,proto3,oneof"`
}

type Channel_Alt1_Link struct {
	Link *Link `protobuf:"bytes,2,opt,name=link,proto3,oneof"`
}

type Channel_Alt1_Description struct {
	Description *Description `protobuf:"bytes,3,opt,name=description,proto3,oneof"`
}

type Channel_Alt1_Language struct {
	Language *Language `protobuf:"bytes,4,opt,name=language,proto3,oneof"`
}

type Channel_Alt1_Copyright struct {
	Copyright *Copyright `protobuf:"bytes,5,opt,name=copyright,proto3,oneof"`
}

type Channel_Alt1_ManagingEditor struct {
	ManagingEditor *ManagingEditor `protobuf:"bytes,6,opt,name=managing_editor,json=managingEditor,proto3,oneof"`
}

type Channel_Alt1_WebMaster struct {
	WebMaster *WebMaster `protobuf:"bytes,7,opt,name=web_master,json=webMaster,proto3,oneof"`
}

type Channel_Alt1_PubDate struct {
	PubDate *PubDate `protobuf:"bytes,8,opt,name=pub_date,json=pubDate,proto3,oneof"`
}

type Channel_Alt1_LastBuildDate struct {
	LastBuildDate *LastBuildDate `protobuf:"bytes,9,opt,name=last_build_date,json=lastBuildDate,proto3,oneof"`
}

type Channel_Alt1_Generator struct {
	Generator *Generator `protobuf:"bytes,10,opt,name=generator,proto3,oneof"`
}

type Channel_Alt1_Docs struct {
	Docs *Docs `protobuf:"bytes,11,opt,name=docs,proto3,oneof"`
}

type Channel_Alt1_Cloud struct {
	Cloud *Cloud `protobuf:"bytes,12,opt,name=cloud,proto3,oneof"`
}

type Channel_Alt1_Ttl struct {
	Ttl *Ttl `protobuf:"bytes,13,opt,name=ttl,proto3,oneof"`
}

type Channel_Alt1_Image struct {
	Image *Image `protobuf:"bytes,14,opt,name=image,proto3,oneof"`
}

type Channel_Alt1_Rating struct {
	Rating *Rating `protobuf:"bytes,15,opt,name=rating,proto3,oneof"`
}

type Channel_Alt1_TextInput struct {
	TextInput *TextInput `protobuf:"bytes,16,opt,name=text_input,json=textInput,proto3,oneof"`
}

type Channel_Alt1_SkipHours struct {
	SkipHours *SkipHours `protobuf:"bytes,17,opt,name=skip_hours,json=skipHours,proto3,oneof"`
}

type Channel_Alt1_SkipDays struct {
	SkipDays *SkipDays `protobuf:"bytes,18,opt,name=skip_days,json=skipDays,proto3,oneof"`
}

type Channel_Alt1_Category struct {
	Category *Category `protobuf:"bytes,19,opt,name=category,proto3,oneof"`
}

type Channel_Alt1_Item struct {
	Item *Item `protobuf:"bytes,20,opt,name=item,proto3,oneof"`
}

func (*Channel_Alt1_Title) isChannel_Alt1_Value() {}

func (*Channel_Alt1_Link) isChannel_Alt1_Value() {}

func (*Channel_Alt1_Description) isChannel_Alt1_Value() {}

func (*Channel_Alt1_Language) isChannel_Alt1_Value() {}

func (*Channel_Alt1_Copyright) isChannel_Alt1_Value() {}

func (*Channel_Alt1_ManagingEditor) isChannel_Alt1_Value() {}

func (*Channel_Alt1_WebMaster) isChannel_Alt1_Value() {}

func (*Channel_Alt1_PubDate) isChannel_Alt1_Value() {}

func (*Channel_Alt1_LastBuildDate) isChannel_Alt1_Value() {}

func (*Channel_Alt1_Generator) isChannel_Alt1_Value() {}

func (*Channel_Alt1_Docs) isChannel_Alt1_Value() {}

func (*Channel_Alt1_Cloud) isChannel_Alt1_Value() {}

func (*Channel_Alt1_Ttl) isChannel_Alt1_Value() {}

func (*Channel_Alt1_Image) isChannel_Alt1_Value() {}

func (*Channel_Alt1_Rating) isChannel_Alt1_Value() {}

func (*Channel_Alt1_TextInput) isChannel_Alt1_Value() {}

func (*Channel_Alt1_SkipHours) isChannel_Alt1_Value() {}

func (*Channel_Alt1_SkipDays) isChannel_Alt1_Value() {}

func (*Channel_Alt1_Category) isChannel_Alt1_Value() {}

func (*Channel_Alt1_Item) isChannel_Alt1_Value() {}

type Item_Alt1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Item_Alt1_Title
	//	*Item_Alt1_Link
	//	*Item_Alt1_Description
	//	*Item_Alt1_Author
	//	*Item_Alt1_Category
	//	*Item_Alt1_Comments
	//	*Item_Alt1_Enclosure
	//	*Item_Alt1_Guid
	//	*Item_Alt1_PubDate
	//	*Item_Alt1_Source
	Value         isItem_Alt1_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item_Alt1) Reset() {
	*x = Item_Alt1{}
	mi := &file_rss_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item_Alt1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item_Alt1) ProtoMessage() {}

func (x *Item_Alt1) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item_Alt1.ProtoReflect.Descriptor instead.
func (*Item_Alt1) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Item_Alt1) GetValue() isItem_Alt1_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Item_Alt1) GetTitle() *Title {
	if x != nil {
		if x, ok := x.Value.(*Item_Alt1_Title); ok {
			return x.Title
		}
	}
	return nil
}

func (x *Item_Alt1) GetLink() *Link {
	if x != nil {
		if x, ok := x.Value.(*Item_Alt1_Link); ok {
			return x.Link
		}
	}
	return nil
}

func (x *Item_Alt1) GetDescription() *Description {
	if x != nil {
		if x, ok := x.Value.(*Item_Alt1_Description); ok {
			return x.Description
		}
	}
	return nil
}

func (x *Item_Alt1) GetAuthor() *Author {
	if x != nil {
		if x, ok := x.Value.(*Item_Alt1_Author); ok {
			return x.Author
		}
	}
	return nil
}

func (x *Item_Alt1) GetCategory() *Category {
	if x != nil {
		if x, ok := x.Value.(*Item_Alt1_Category); ok {
			return x.Category
		}
	}
	return nil
}

func (x *Item_Alt1) GetComments() *Comments {
	if x != nil {
		if x, ok := x.Value.(*Item_Alt1_Comments); ok {
			return x.Comments
		}
	}
	return nil
}

func (x *Item_Alt1) GetEnclosure() *Enclosure {
	if x != nil {
		if x, ok := x.Value.(*Item_Alt1_Enclosure); ok {
			return x.Enclosure
		}
	}
	return nil
}

func (x *Item_Alt1) GetGuid() *Guid {
	if x != nil {
		if x, ok := x.Value.(*Item_Alt1_Guid); ok {
			return x.Guid
		}
	}
	return nil
}

func (x *Item_Alt1) GetPubDate() *PubDate {
	if x != nil {
		if x, ok := x.Value.(*Item_Alt1_PubDate); ok {
			return x.PubDate
		}
	}
	return nil
}

func (x *Item_Alt1) GetSource() *Source {
	if x != nil {
		if x, ok := x.Value.(*Item_Alt1_Source); ok {
			return x.Source
		}
	}
	return nil
}

type isItem_Alt1_Value interface {
	isItem_Alt1_Value()
}

type Item_Alt1_Title struct {
	Title *Title `protobuf:"bytes,1,opt,name=title,proto3,oneof"`
}

type Item_Alt1_Link struct {
	Link *Link `protobuf:"bytes,2,opt,name=link,proto3,oneof"`
}

type Item_Alt1_Description struct {
	Description *Description `protobuf:"bytes,3,opt,name=description,proto3,oneof"`
}

type Item_Alt1_Author struct {
	Author *Author `protobuf:"bytes,4,opt,name=author,proto3,oneof"`
}

type Item_Alt1_Category struct {
	Category *Category `protobuf:"bytes,5,opt,name=category,proto3,oneof"`
}

type Item_Alt1_Comments struct {
	Comments *Comments `protobuf:"bytes,6,opt,name=comments,proto3,oneof"`
}

type Item_Alt1_Enclosure struct {
	Enclosure *Enclosure `protobuf:"bytes,7,opt,name=enclosure,proto3,oneof"`
}

type Item_Alt1_Guid struct {
	Guid *Guid `protobuf:"bytes,8,opt,name=guid,proto3,oneof"`
}

type Item_Alt1_PubDate struct {
	PubDate *PubDate `protobuf:"bytes,9,opt,name=pub_date,json=pubDate,proto3,oneof"`
}

type Item_Alt1_Source struct {
	Source *Source `protobuf:"bytes,10,opt,name=source,proto3,oneof"`
}

func (*Item_Alt1_Title) isItem_Alt1_Value() {}

func (*Item_Alt1_Link) isItem_Alt1_Value() {}

func (*Item_Alt1_Description) isItem_Alt1_Value() {}

func (*Item_Alt1_Author) isItem_Alt1_Value() {}

func (*Item_Alt1_Category) isItem_Alt1_Value() {}

func (*Item_Alt1_Comments) isItem_Alt1_Value() {}

func (*Item_Alt1_Enclosure) isItem_Alt1_Value() {}

func (*Item_Alt1_Guid) isItem_Alt1_Value() {}

func (*Item_Alt1_PubDate) isItem_Alt1_Value() {}

func (*Item_Alt1_Source) isItem_Alt1_Value() {}

type Image_Alt1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Image_Alt1_Url
	//	*Image_Alt1_Title
	//	*Image_Alt1_Link
	//	*Image_Alt1_Width
	//	*Image_Alt1_Height
	//	*Image_Alt1_Description
	Value         isImage_Alt1_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image_Alt1) Reset() {
	*x = Image_Alt1{}
	mi := &file_rss_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image_Alt1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image_Alt1) ProtoMessage() {}

func (x *Image_Alt1) ProtoReflect() protoreflect.Message {
	mi := &file_rss_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image_Alt1.ProtoReflect.Descriptor instead.
func (*Image_Alt1) Descriptor() ([]byte, []int) {
	return file_rss_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Image_Alt1) GetValue() isImage_Alt1_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Image_Alt1) GetUrl() *Url {
	if x != nil {
		if x, ok := x.Value.(*Image_Alt1_Url); ok {
			return x.Url
		}
	}
	return nil
}

func (x *Image_Alt1) GetTitle() *Title {
	if x != nil {
		if x, ok := x.Value.(*Image_Alt1_Title); ok {
			return x.Title
		}
	}
	return nil
}

func (x *Image_Alt1) GetLink() *Link {
	if x != nil {
		if x, ok := x.Value.(*Image_Alt1_Link); ok {
			return x.Link
		}
	}
	return nil
}

func (x *Image_Alt1) GetWidth() *Width {
	if x != nil {
		if x, ok := x.Value.(*Image_Alt1_Width); ok {
			return x.Width
		}
	}
	return nil
}

func (x *Image_Alt1) GetHeight() *Height {
	if x != nil {
		if x, ok := x.Value.(*Image_Alt1_Height); ok {
			return x.Height
		}
	}
	return nil
}

func (x *Image_Alt1) GetDescription() *Description {
	if x != nil {
		if x, ok := x.Value.(*Image_Alt1_Description); ok {
			return x.Description
		}
	}
	return nil
}

type isImage_Alt1_Value interface {
	isImage_Alt1_Value()
}

type Image_Alt1_Url struct {
	Url *Url `protobuf:"bytes,1,opt,name=url,proto3,oneof"`
}

type Image_Alt1_Title struct {
	Title *Title `protobuf:"bytes,2,opt,name=title,proto3,oneof"`
}

type Image_Alt1_Link struct {
	Link *Link `protobuf:"bytes,3,opt,name=link,proto3,oneof"`
}

type Image_Alt1_Width struct {
	Width *Width `protobuf:"bytes,4,opt,name=width,proto3,oneof"`
}

type Image_Alt1_Height struct {
	Height *Height `protobuf:"bytes,5,opt,name=height,proto3,oneof"`
}

type Image_Alt1_Description struct {
	Description *Description `protobuf:"bytes,6,opt,name=description,proto3,oneof"`
}

func (*Image_Alt1_Url) isImage_Alt1_Value() {}

func (*Image_Alt1_Title) isImage_Alt1_Value() {}

func (*Image_Alt1_Link) isImage_Alt1_Value() {}

func (*Image_Alt1_Width) isImage_Alt1_Value() {}

func (*Image_Alt1_Height) isImage_Alt1_Value() {}

func (*Image_Alt1_Description) isImage_Alt1_Value() {}

var File_rss_proto protoreflect.FileDescriptor

const file_rss_proto_rawDesc = "" +
	"\n" +
	"\trss.proto\x12\x03rss\"G\n" +
	"\x03Rss\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12&\n" +
	"\achannel\x18\x02 \x01(\v2\f.rss.ChannelR\achannel\"\xb0\a\n" +
	"\aChannel\x12%\n" +
	"\x04alt1\x18\x01 \x03(\v2\x11.rss.Channel.Alt1R\x04alt1\x1a\xfd\x06\n" +
	"\x04Alt1\x12\"\n" +
	"\x05title\x18\x01 \x01(\v2\n" +
	".rss.TitleH\x00R\x05title\x12\x1f\n" +
	"\x04link\x18\x02 \x01(\v2\t.rss.LinkH\x00R\x04link\x124\n" +
	"\vdescription\x18\x03 \x01(\v2\x10.rss.DescriptionH\x00R\vdescription\x12+\n" +
	"\blanguage\x18\x04 \x01(\v2\r.rss.LanguageH\x00R\blanguage\x12.\n" +
	"\tcopyright\x18\x05 \x01(\v2\x0e.rss.CopyrightH\x00R\tcopyright\x12>\n" +
	"\x0fmanaging_editor\x18\x06 \x01(\v2\x13.rss.ManagingEditorH\x00R\x0emanagingEditor\x12/\n" +
	"\n" +
	"web_master\x18\a \x01(\v2\x0e.rss.WebMasterH\x00R\twebMaster\x12)\n" +
	"\bpub_date\x18\b \x01(\v2\f.rss.PubDateH\x00R\apubDate\x12<\n" +
	"\x0flast_build_date\x18\t \x01(\v2\x12.rss.LastBuildDateH\x00R\rlastBuildDate\x12.\n" +
	"\tgenerator\x18\n" +
	" \x01(\v2\x0e.rss.GeneratorH\x00R\tgenerator\x12\x1f\n" +
	"\x04docs\x18\v \x01(\v2\t.rss.DocsH\x00R\x04docs\x12\"\n" +
	"\x05cloud\x18\f \x01(\v2\n" +
	".rss.CloudH\x00R\x05cloud\x12\x1c\n" +
	"\x03ttl\x18\r \x01(\v2\b.rss.TtlH\x00R\x03ttl\x12\"\n" +
	"\x05image\x18\x0e \x01(\v2\n" +
	".rss.ImageH\x00R\x05image\x12%\n" +
	"\x06rating\x18\x0f \x01(\v2\v.rss.RatingH\x00R\x06rating\x12/\n" +
	"\n" +
	"text_input\x18\x10 \x01(\v2\x0e.rss.TextInputH\x00R\ttextInput\x12/\n" +
	"\n" +
	"skip_hours\x18\x11 \x01(\v2\x0e.rss.SkipHoursH\x00R\tskipHours\x12,\n" +
	"\tskip_days\x18\x12 \x01(\v2\r.rss.SkipDaysH\x00R\bskipDays\x12+\n" +
	"\bcategory\x18\x13 \x01(\v2\r.rss.CategoryH\x00R\bcategory\x12\x1f\n" +
	"\x04item\x18\x14 \x01(\v2\t.rss.ItemH\x00R\x04itemB\a\n" +
	"\x05value\"\xdb\x03\n" +
	"\x04Item\x12\"\n" +
	"\x04alt1\x18\x01 \x03(\v2\x0e.rss.Item.Alt1R\x04alt1\x1a\xae\x03\n" +
	"\x04Alt1\x12\"\n" +
	"\x05title\x18\x01 \x01(\v2\n" +
	".rss.TitleH\x00R\x05title\x12\x1f\n" +
	"\x04link\x18\x02 \x01(\v2\t.rss.LinkH\x00R\x04link\x124\n" +
	"\vdescription\x18\x03 \x01(\v2\x10.rss.DescriptionH\x00R\vdescription\x12%\n" +
	"\x06author\x18\x04 \x01(\v2\v.rss.AuthorH\x00R\x06author\x12+\n" +
	"\bcategory\x18\x05 \x01(\v2\r.rss.CategoryH\x00R\bcategory\x12+\n" +
	"\bcomments\x18\x06 \x01(\v2\r.rss.CommentsH\x00R\bcomments\x12.\n" +
	"\tenclosure\x18\a \x01(\v2\x0e.rss.EnclosureH\x00R\tenclosure\x12\x1f\n" +
	"\x04guid\x18\b \x01(\v2\t.rss.GuidH\x00R\x04guid\x12)\n" +
	"\bpub_date\x18\t \x01(\v2\f.rss.PubDateH\x00R\apubDate\x12%\n" +
	"\x06source\x18\n" +
	" \x01(\v2\v.rss.SourceH\x00R\x06sourceB\a\n" +
	"\x05value\"\xa2\x02\n" +
	"\x05Image\x12#\n" +
	"\x04alt1\x18\x01 \x03(\v2\x0f.rss.Image.Alt1R\x04alt1\x1a\xf3\x01\n" +
	"\x04Alt1\x12\x1c\n" +
	"\x03url\x18\x01 \x01(\v2\b.rss.UrlH\x00R\x03url\x12\"\n" +
	"\x05title\x18\x02 \x01(\v2\n" +
	".rss.TitleH\x00R\x05title\x12\x1f\n" +
	"\x04link\x18\x03 \x01(\v2\t.rss.LinkH\x00R\x04link\x12\"\n" +
	"\x05width\x18\x04 \x01(\v2\n" +
	".rss.WidthH\x00R\x05width\x12%\n" +
	"\x06height\x18\x05 \x01(\v2\v.rss.HeightH\x00R\x06height\x124\n" +
	"\vdescription\x18\x06 \x01(\v2\x10.rss.DescriptionH\x00R\vdescriptionB\a\n" +
	"\x05value\"\x9f\x01\n" +
	"\tTextInput\x12 \n" +
	"\x05title\x18\x01 \x01(\v2\n" +
	".rss.TitleR\x05title\x122\n" +
	"\vdescription\x18\x02 \x01(\v2\x10.rss.DescriptionR\vdescription\x12\x1d\n" +
	"\x04name\x18\x03 \x01(\v2\t.rss.NameR\x04name\x12\x1d\n" +
	"\x04link\x18\x04 \x01(\v2\t.rss.LinkR\x04link\"\x92\x01\n" +
	"\x05Cloud\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04port\x18\x02 \x01(\tR\x04port\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12-\n" +
	"\x12register_procedure\x18\x04 \x01(\tR\x11registerProcedure\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\"I\n" +
	"\tEnclosure\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06length\x18\x02 \x01(\tR\x06length\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\".\n" +
	"\x06Source\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"6\n" +
	"\bCategory\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\">\n" +
	"\x04Guid\x12\"\n" +
	"\ris_perma_link\x18\x01 \x01(\tR\visPermaLink\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"*\n" +
	"\tSkipHours\x12\x1d\n" +
	"\x04hour\x18\x01 \x03(\v2\t.rss.HourR\x04hour\"&\n" +
	"\bSkipDays\x12\x1a\n" +
	"\x03day\x18\x01 \x03(\v2\b.rss.DayR\x03day\"\x1b\n" +
	"\x05Title\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1a\n" +
	"\x04Link\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"!\n" +
	"\vDescription\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1e\n" +
	"\bLanguage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1f\n" +
	"\tCopyright\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"$\n" +
	"\x0eManagingEditor\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1f\n" +
	"\tWebMaster\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1d\n" +
	"\aPubDate\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"#\n" +
	"\rLastBuildDate\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1f\n" +
	"\tGenerator\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1a\n" +
	"\x04Docs\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x19\n" +
	"\x03Ttl\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1c\n" +
	"\x06Rating\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x19\n" +
	"\x03Url\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1b\n" +
	"\x05Width\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1c\n" +
	"\x06Height\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1a\n" +
	"\x04Name\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1c\n" +
	"\x06Author\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1e\n" +
	"\bComments\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1a\n" +
	"\x04Hour\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x19\n" +
	"\x03Day\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04textB1Z/github.com/accretional/xmile/proto/pb/rss;rsspbb\x06proto3"

var (
	file_rss_proto_rawDescOnce sync.Once
	file_rss_proto_rawDescData []byte
)

func file_rss_proto_rawDescGZIP() []byte {
	file_rss_proto_rawDescOnce.Do(func() {
		file_rss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rss_proto_rawDesc), len(file_rss_proto_rawDesc)))
	})
	return file_rss_proto_rawDescData
}

var file_rss_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_rss_proto_goTypes = []any{
	(*Rss)(nil),            // 0: rss.Rss
	(*Channel)(nil),        // 1: rss.Channel
	(*Item)(nil),           // 2: rss.Item
	(*Image)(nil),          // 3: rss.Image
	(*TextInput)(nil),      // 4: rss.TextInput
	(*Cloud)(nil),          // 5: rss.Cloud
	(*Enclosure)(nil),      // 6: rss.Enclosure
	(*Source)(nil),         // 7: rss.Source
	(*Category)(nil),       // 8: rss.Category
	(*Guid)(nil),           // 9: rss.Guid
	(*SkipHours)(nil),      // 10: rss.SkipHours
	(*SkipDays)(nil),       // 11: rss.SkipDays
	(*Title)(nil),          // 12: rss.Title
	(*Link)(nil),           // 13: rss.Link
	(*Description)(nil),    // 14: rss.Description
	(*Language)(nil),       // 15: rss.Language
	(*Copyright)(nil),      // 16: rss.Copyright
	(*ManagingEditor)(nil), // 17: rss.ManagingEditor
	(*WebMaster)(nil),      // 18: rss.WebMaster
	(*PubDate)(nil),        // 19: rss.PubDate
	(*LastBuildDate)(nil),  // 20: rss.LastBuildDate
	(*Generator)(nil),      // 21: rss.Generator
	(*Docs)(nil),           // 22: rss.Docs
	(*Ttl)(nil),            // 23: rss.Ttl
	(*Rating)(nil),         // 24: rss.Rating
	(*Url)(nil),            // 25: rss.Url
	(*Width)(nil),          // 26: rss.Width
	(*Height)(nil),         // 27: rss.Height
	(*Name)(nil),           // 28: rss.Name
	(*Author)(nil),         // 29: rss.Author
	(*Comments)(nil),       // 30: rss.Comments
	(*Hour)(nil),           // 31: rss.Hour
	(*Day)(nil),            // 32: rss.Day
	(*Channel_Alt1)(nil),   // 33: rss.Channel.Alt1
	(*Item_Alt1)(nil),      // 34: rss.Item.Alt1
	(*Image_Alt1)(nil),     // 35: rss.Image.Alt1
}
var file_rss_proto_depIdxs = []int32{
	1,  // 0: rss.Rss.channel:type_name -> rss.Channel
	33, // 1: rss.Channel.alt1:type_name -> rss.Channel.Alt1
	34, // 2: rss.Item.alt1:type_name -> rss.Item.Alt1
	35, // 3: rss.Image.alt1:type_name -> rss.Image.Alt1
	12, // 4: rss.TextInput.title:type_name -> rss.Title
	14, // 5: rss.TextInput.description:type_name -> rss.Description
	28, // 6: rss.TextInput.name:type_name -> rss.Name
	13, // 7: rss.TextInput.link:type_name -> rss.Link
	31, // 8: rss.SkipHours.hour:type_name -> rss.Hour
	32, // 9: rss.SkipDays.day:type_name -> rss.Day
	12, // 10: rss.Channel.Alt1.title:type_name -> rss.Title
	13, // 11: rss.Channel.Alt1.link:type_name -> rss.Link
	14, // 12: rss.Channel.Alt1.description:type_name -> rss.Description
	15, // 13: rss.Channel.Alt1.language:type_name -> rss.Language
	16, // 14: rss.Channel.Alt1.copyright:type_name -> rss.Copyright
	17, // 15: rss.Channel.Alt1.managing_editor:type_name -> rss.ManagingEditor
	18, // 16: rss.Channel.Alt1.web_master:type_name -> rss.WebMaster
	19, // 17: rss.Channel.Alt1.pub_date:type_name -> rss.PubDate
	20, // 18: rss.Channel.Alt1.last_build_date:type_name -> rss.LastBuildDate
	21, // 19: rss.Channel.Alt1.generator:type_name -> rss.Generator
	22, // 20: rss.Channel.Alt1.docs:type_name -> rss.Docs
	5,  // 21: rss.Channel.Alt1.cloud:type_name -> rss.Cloud
	23, // 22: rss.Channel.Alt1.ttl:type_name -> rss.Ttl
	3,  // 23: rss.Channel.Alt1.image:type_name -> rss.Image
	24, // 24: rss.Channel.Alt1.rating:type_name -> rss.Rating
	4,  // 25: rss.Channel.Alt1.text_input:type_name -> rss.TextInput
	10, // 26: rss.Channel.Alt1.skip_hours:type_name -> rss.SkipHours
	11, // 27: rss.Channel.Alt1.skip_days:type_name -> rss.SkipDays
	8,  // 28: rss.Channel.Alt1.category:type_name -> rss.Category
	2,  // 29: rss.Channel.Alt1.item:type_name -> rss.Item
	12, // 30: rss.Item.Alt1.title:type_name -> rss.Title
	13, // 31: rss.Item.Alt1.link:type_name -> rss.Link
	14, // 32: rss.Item.Alt1.description:type_name -> rss.Description
	29, // 33: rss.Item.Alt1.author:type_name -> rss.Author
	8,  // 34: rss.Item.Alt1.category:type_name -> rss.Category
	30, // 35: rss.Item.Alt1.comments:type_name -> rss.Comments
	6,  // 36: rss.Item.Alt1.enclosure:type_name -> rss.Enclosure
	9,  // 37: rss.Item.Alt1.guid:type_name -> rss.Guid
	19, // 38: rss.Item.Alt1.pub_date:type_name -> rss.PubDate
	7,  // 39: rss.Item.Alt1.source:type_name -> rss.Source
	25, // 40: rss.Image.Alt1.url:type_name -> rss.Url
	12, // 41: rss.Image.Alt1.title:type_name -> rss.Title
	13, // 42: rss.Image.Alt1.link:type_name -> rss.Link
	26, // 43: rss.Image.Alt1.width:type_name -> rss.Width
	27, // 44: rss.Image.Alt1.height:type_name -> rss.Height
	14, // 45: rss.Image.Alt1.description:type_name -> rss.Description
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_rss_proto_init() }
func file_rss_proto_init() {
	if File_rss_proto != nil {
		return
	}
	file_rss_proto_msgTypes[33].OneofWrappers = []any{
		(*Channel_Alt1_Title)(nil),
		(*Channel_Alt1_Link)(nil),
		(*Channel_Alt1_Description)(nil),
		(*Channel_Alt1_Language)(nil),
		(*Channel_Alt1_Copyright)(nil),
		(*Channel_Alt1_ManagingEditor)(nil),
		(*Channel_Alt1_WebMaster)(nil),
		(*Channel_Alt1_PubDate)(nil),
		(*Channel_Alt1_LastBuildDate)(nil),
		(*Channel_Alt1_Generator)(nil),
		(*Channel_Alt1_Docs)(nil),
		(*Channel_Alt1_Cloud)(nil),
		(*Channel_Alt1_Ttl)(nil),
		(*Channel_Alt1_Image)(nil),
		(*Channel_Alt1_Rating)(nil),
		(*Channel_Alt1_TextInput)(nil),
		(*Channel_Alt1_SkipHours)(nil),
		(*Channel_Alt1_SkipDays)(nil),
		(*Channel_Alt1_Category)(nil),
		(*Channel_Alt1_Item)(nil),
	}
	file_rss_proto_msgTypes[34].OneofWrappers = []any{
		(*Item_Alt1_Title)(nil),
		(*Item_Alt1_Link)(nil),
		(*Item_Alt1_Description)(nil),
		(*Item_Alt1_Author)(nil),
		(*Item_Alt1_Category)(nil),
		(*Item_Alt1_Comments)(nil),
		(*Item_Alt1_Enclosure)(nil),
		(*Item_Alt1_Guid)(nil),
		(*Item_Alt1_PubDate)(nil),
		(*Item_Alt1_Source)(nil),
	}
	file_rss_proto_msgTypes[35].OneofWrappers = []any{
		(*Image_Alt1_Url)(nil),
		(*Image_Alt1_Title)(nil),
		(*Image_Alt1_Link)(nil),
		(*Image_Alt1_Width)(nil),
		(*Image_Alt1_Height)(nil),
		(*Image_Alt1_Description)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rss_proto_rawDesc), len(file_rss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rss_proto_goTypes,
		DependencyIndexes: file_rss_proto_depIdxs,
		MessageInfos:      file_rss_proto_msgTypes,
	}.Build()
	File_rss_proto = out.File
	file_rss_proto_goTypes = nil
	file_rss_proto_depIdxs = nil
}
