syntax = "proto3";

package rss;

option go_package = "github.com/accretional/xmile/proto/pb/rss;rsspb";

message Rss {
  string version = 1;

  Channel channel = 2;
}

message Channel {
  repeated Alt1 alt1 = 1;

  message Alt1 {
    oneof value {
      Title title = 1;

      Link link = 2;

      Description description = 3;

      Language language = 4;

      Copyright copyright = 5;

      ManagingEditor managing_editor = 6;

      WebMaster web_master = 7;

      PubDate pub_date = 8;

      LastBuildDate last_build_date = 9;

      Generator generator = 10;

      Docs docs = 11;

      Cloud cloud = 12;

      Ttl ttl = 13;

      Image image = 14;

      Rating rating = 15;

      TextInput text_input = 16;

      SkipHours skip_hours = 17;

      SkipDays skip_days = 18;

      Category category = 19;

      Item item = 20;
    }
  }
}

message Item {
  repeated Alt1 alt1 = 1;

  message Alt1 {
    oneof value {
      Title title = 1;

      Link link = 2;

      Description description = 3;

      Author author = 4;

      Category category = 5;

      Comments comments = 6;

      Enclosure enclosure = 7;

      Guid guid = 8;

      PubDate pub_date = 9;

      Source source = 10;
    }
  }
}

message Image {
  repeated Alt1 alt1 = 1;

  message Alt1 {
    oneof value {
      Url url = 1;

      Title title = 2;

      Link link = 3;

      Width width = 4;

      Height height = 5;

      Description description = 6;
    }
  }
}

message TextInput {
  Title title = 1;

  Description description = 2;

  Name name = 3;

  Link link = 4;
}

message Cloud {
  string domain = 1;

  string port = 2;

  string path = 3;

  string register_procedure = 4;

  string protocol = 5;
}

message Enclosure {
  string url = 1;

  string length = 2;

  string type = 3;
}

message Source {
  string url = 1;

  string text = 2;
}

message Category {
  string domain = 1;

  string text = 2;
}

message Guid {
  string is_perma_link = 1;

  string text = 2;
}

message SkipHours {
  repeated Hour hour = 1;
}

message SkipDays {
  repeated Day day = 1;
}

message Title {
  string text = 1;
}

message Link {
  string text = 1;
}

message Description {
  string text = 1;
}

message Language {
  string text = 1;
}

message Copyright {
  string text = 1;
}

message ManagingEditor {
  string text = 1;
}

message WebMaster {
  string text = 1;
}

message PubDate {
  string text = 1;
}

message LastBuildDate {
  string text = 1;
}

message Generator {
  string text = 1;
}

message Docs {
  string text = 1;
}

message Ttl {
  string text = 1;
}

message Rating {
  string text = 1;
}

message Url {
  string text = 1;
}

message Width {
  string text = 1;
}

message Height {
  string text = 1;
}

message Name {
  string text = 1;
}

message Author {
  string text = 1;
}

message Comments {
  string text = 1;
}

message Hour {
  string text = 1;
}

message Day {
  string text = 1;
}
