// Package lex is the generic lexical-matcher engine. It carries NO XML or
// DTD knowledge: it interprets a data table (generated by genproto from
// lang/*.lex into proto/pb/*/lexical.go) into gluon token matchers.
//
// Five matcher kinds cover every lexical run XML/DTD needs:
//
//	run       maximal run of 1+ chars in a set of ranges        (S, Nmtoken)
//	name      a start-class char, then start-or-rest chars       (Name)
//	except    maximal run of 1+ chars, none in a stop byte set   (CharData, …)
//	until     chars up to (not including) a fixed delimiter      (comment_text, …)
//	balanced  the XML DOCTYPE internal-subset scan               (dtd_text)
package lex

import (
	"strings"
	"unicode/utf8"
)

// Range is an inclusive codepoint range.
type Range struct{ Lo, Hi rune }

// Matcher is one lexical rule. Only the fields relevant to Kind are set.
type Matcher struct {
	Kind   string  // run | name | except | until | balanced
	Ranges []Range // run: allowed set; name: start-class
	Rest   []Range // name: additional chars valid after the first
	Stops  string  // except: forbidden bytes
	Delim  string  // until: terminator
}

// Func is gluon's token-matcher signature: given source and a position,
// return the matched text and the new position, or ("", -1) for no match.
type Func = func(src string, pos int) (string, int)

// Table builds a runtime matcher for every entry in m.
func Table(m map[string]Matcher) map[string]Func {
	out := make(map[string]Func, len(m))
	for k, v := range m {
		out[k] = v.build()
	}
	return out
}

// Contains reports whether r falls in the matcher's Ranges (used for
// character-legality checks).
func (m Matcher) Contains(r rune) bool { return in(r, m.Ranges) }

func in(r rune, rs []Range) bool {
	for _, x := range rs {
		if r >= x.Lo && r <= x.Hi {
			return true
		}
	}
	return false
}

func (m Matcher) build() Func {
	switch m.Kind {
	case "run":
		rs := m.Ranges
		return func(src string, pos int) (string, int) {
			start := pos
			for pos < len(src) {
				r, sz := utf8.DecodeRuneInString(src[pos:])
				if sz == 0 || !in(r, rs) {
					break
				}
				pos += sz
			}
			if pos == start {
				return "", -1
			}
			return src[start:pos], pos
		}

	case "name":
		st, rt := m.Ranges, m.Rest
		return func(src string, pos int) (string, int) {
			start := pos
			r, sz := utf8.DecodeRuneInString(src[pos:])
			if sz == 0 || !in(r, st) {
				return "", -1
			}
			pos += sz
			for pos < len(src) {
				r, sz = utf8.DecodeRuneInString(src[pos:])
				if sz == 0 || (!in(r, st) && !in(r, rt)) {
					break
				}
				pos += sz
			}
			return src[start:pos], pos
		}

	case "except":
		stops := m.Stops
		return func(src string, pos int) (string, int) {
			start := pos
			for pos < len(src) && strings.IndexByte(stops, src[pos]) < 0 {
				pos++
			}
			if pos == start {
				return "", -1
			}
			return src[start:pos], pos
		}

	case "until":
		delim := m.Delim
		return func(src string, pos int) (string, int) {
			i := strings.Index(src[pos:], delim)
			if i < 0 {
				return "", -1
			}
			return src[pos : pos+i], pos + i
		}

	case "balanced":
		return balanced
	}

	return func(string, int) (string, int) { return "", -1 }
}

// balanced scans the internal-subset span of a DOCTYPE up to (not
// including) the closing '>' at bracket depth 0, skipping comments, PIs and
// quoted literals so their '>' / brackets do not count.
func balanced(src string, pos int) (string, int) {
	start := pos
	depth := 0
	for pos < len(src) {
		if strings.HasPrefix(src[pos:], "<!--") {
			i := strings.Index(src[pos+4:], "-->")
			if i < 0 {
				return "", -1
			}
			pos += 4 + i + 3
			continue
		}
		if strings.HasPrefix(src[pos:], "<?") {
			i := strings.Index(src[pos+2:], "?>")
			if i < 0 {
				return "", -1
			}
			pos += 2 + i + 2
			continue
		}
		switch c := src[pos]; c {
		case '"', '\'':
			pos++
			for pos < len(src) && src[pos] != c {
				pos++
			}
			if pos >= len(src) {
				return "", -1
			}
		case '[':
			depth++
		case ']':
			if depth > 0 {
				depth--
			}
		case '>':
			if depth == 0 {
				return src[start:pos], pos
			}
		}
		pos++
	}
	return "", -1
}
